### ISSUE TITLE
Undefined control sequence \lstdefinestyle

### ISSUE THREAD

**Issue by abulgatz** [Wandmalfarbe/pandoc-latex-template#1]
Getting an error:
`! Undefined control sequence.
l.224 \lstdefinestyle`

**Comment by Wandmalfarbe** [comment]
Thank you for reporting this. I hope my commit fixes your problem.

**Comment by abulgatz** [comment]
It does!

Separate question: how do you get the line numbers and the background and borders around your code that you have in your preview?

Love the template by the way!

**Comment by Wandmalfarbe** [comment]
Great! You can get the custom formatted code by using the "--listings" option just like in the example code from the readme.

I'm glad you love the template!

**Comment by abulgatz** [comment]
Thanks.

Might want to add a description of exactly what "--listings" does to the readme, and also might want to mention changing the language from german"

**Comment by Wandmalfarbe** [comment]
Yes that would definitely be helpful. Thank you for these suggestions.
