### ISSUE TITLE
Quoted blocks

### ISSUE THREAD

**Issue by jmatsushita** [Wandmalfarbe/pandoc-latex-template#10]
Hi,

Thanks for the great template! It would be great to have an either box style `>` quoted block or a sideline "a la github". Currently using markdown quotes doesn't change any style.

Cheers,

Jun

**Comment by Wandmalfarbe** [comment]
I agree that a style for quoted blocks would be nice. The box looks good. I added a comment on your pull request.

**Comment by Wandmalfarbe** [comment]
There is now a style for block quotations one can see [in the example pdf](https://github.com/Wandmalfarbe/pandoc-latex-template/blob/master/examples/basic-example/basic-example.pdf).
