### ISSUE TITLE
Not compatible with --top-level-division=[chapter|part]

### ISSUE THREAD

**Issue by noraj** [Wandmalfarbe/pandoc-latex-template#102]
Here is my rmarkdown file:

~~~rmarkdown
---
title: "report"
author: "author"
date: June 30, 2019
output:
  pdf_document:
    keep_tex: true
    toc: true
    toc_depth: 6
    highlight: "zenburn"
    number_sections: true
    pandoc_args: ["--top-level-division=chapter"]
    template: eisvogel.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GitHub Documents

This is an R Markdown format used for publishing markdown documents to GitHub. When you click the **Knit** button all R code chunks are run and a markdown file (.md) suitable for publishing to GitHub is generated.

## Including Code

You can include R code in the document as follows:

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
~~~

And here is the R markdown console output from Rstudio:

```
/usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS test.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output test.tex --table-of-contents --toc-depth 6 --template eisvogel.tex --number-sections --highlight-style zenburn --pdf-engine pdflatex --top-level-division=chapter 
output file: test.knit.md

! Undefined control sequence.
l.315 \frontmatter

Error: Failed to compile test.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips. See test.log for more info.
Execution halted
```

PDF export works fine without using this theme.

**Comment by noraj** [comment]
I found the problem: this is the `--top-level-division=chapter` pandoc argument. Without it works with Rmarkdown from Rstudio or with pure markdown directly with pandoc, but with it even pure markdown with pandoc fails.

**Comment by Wandmalfarbe** [comment]
The option `--top-level-division=chapter` tells pandoc to generate a `\chapter{...}` for every top level heading in your document. Chapters are only supported in books. You have to add `book: true` to your YAML frontmatter to render a book:

```markdown
---
title: "report"
author: "author"
date: June 30, 2019
book: true
classoption: oneside
output:
  pdf_document:
    keep_tex: true
    toc: true
    toc_depth: 6
    highlight: "zenburn"
    number_sections: true
    pandoc_args: ["--top-level-division=chapter"]
    template: eisvogel.tex
---
```

I also added `classoption: oneside` to render a onsided document.

**Comment by noraj** [comment]
@Wandmalfarbe 

![image](https://user-images.githubusercontent.com/16578570/60400797-41df1d80-9b79-11e9-8f65-541a4dbff095.png)

From https://pandoc.org/MANUAL.html

> When the LaTeX document class is set to report, book, or memoir (unless the article option is specified), chapter is implied as the setting for this option.

Not only book, but also report and memoir.

**Comment by Wandmalfarbe** [comment]
Yes, that's true. But this template only has support for the document classes `scrartcl` and `scrbook`.
