### ISSUE TITLE
Missing background.pdf file in custom-titlepage example

### ISSUE THREAD

**Issue by seishonagon** [Wandmalfarbe/pandoc-latex-template#108]
Hi, the examples don't compile properly: you'r missing the background.pdf file in the folder custom-titlepage. 
Moving a copy from titlepage-backgrounds seems to work

**Comment by Wandmalfarbe** [comment]
Thank you for reporting this issue. I fixed it in commit 94346284759d5401218192befd9615db9aa1b683.
