### ISSUE TITLE
headers/footers and text colour

### ISSUE THREAD

**Issue by giuliagrisot** [Wandmalfarbe/pandoc-latex-template#109]
hi, what should I add to my pandoc command using your template to remove footer text from both right and left, and to change the upper one to page-number? and alaos, can i change the text colour for quotes (and for everything else) to just black? thanks!

**Comment by Wandmalfarbe** [comment]
> what should I add to my pandoc command using your template to remove footer text from both right and left, and to change the upper one to page-number?

I added an example to show how to change the header and footer. You can use the variables `header-left`, `header-center`, `header-right`, `footer-left` and so on.

```markdown
---
title: "Example PDF"
author: [Author]
date: "2017-02-20"
subject: "Markdown"
keywords: [Markdown, Example]
header-left: "\\hspace{1cm}"
header-center: "\\leftmark"
header-right: "Page \\thepage"
footer-left: "\\thetitle"
footer-center: "This is \\LaTeX{}"
footer-right: "\\theauthor"
...

# Vinaque sanguine metuenti cuiquam Alcyone fixus
```

The text inside these variables is interpreted as markdown so you could use `header-left: "**Bold Text**"` to get bold text. When inserting raw LaTeX we don't want pandoc to interpret it as markdown so escaping of `\thetitle` to `\\thetitle` is necessary. Unfortunately it is not possible to override the default value by using an empty string like this `header-left: ""`. So I use a trick to insert the command `\hspace{1cm}` which produces an (invisible) space of 1 cm.

> can i change the text colour for quotes (and for everything else) to just black?

Please open a new issue for that feature. It is currently not possible to change the color of blockquotes.
