### ISSUE TITLE
TOC colors

### ISSUE THREAD

**Issue by abers** [Wandmalfarbe/pandoc-latex-template#113]
I have been trying to add colours to the TOC without success. I have extremely minimal LaTeX skills, so I am likely doing something wrong. What I want to achieve is for the chapter titles and chapter page numbers to be, say, red but the rest (dots, section titles, section page numbers, etc) to remain black.

**Comment by Wandmalfarbe** [comment]
Pandoc has builtin support for coloring all of the toc entries.. You just have to set the variable `toccolor` to the color you like.

```markdown
---
title: "Example PDF"
author: [Author]
date: "2017-02-20"
subject: "Markdown"
keywords: [Markdown, Example]
toc: true,
toccolor: Cerulean
...

# Some Heading

Lorem Ipsum ...
```

A list of supported color names is in [the xcolor manual (Chapter 4: Colors by Name).](http://mirrors.ctan.org/macros/latex/contrib/xcolor/xcolor.pdf) You can use all named colors from the three groups: `dvipsnames`, `svgnames`, `x11names`.

Unfortunately I dont know how to change the coloring of chapters and sections independently (though I beliefe it is certainly possible with LaTeX).
