### ISSUE TITLE
Question: support of YAML config as pandoc command line arguments?

### ISSUE THREAD

**Issue by cavo789** [Wandmalfarbe/pandoc-latex-template#117]
Good morning.

I've made a lot of .md documentations for my company and I wish to be able to specify the logo not in my document but as command line arguments.

So, in my .md, I've this:

```markdown
logo: "logo.pdf"
logo-width: "200"
```

But I need to put these two lines in all my markdown files...

Is it possible to specify YAML arguments as pandoc arguments like in: 

```
pandoc example.md -o example.pdf --from markdown --template eisvogel --listings --logo logo.pdf
```

Many thanks!!!

**Comment by cavo789** [comment]
Found after posting here... https://github.com/jgm/pandoc/issues/1960#issuecomment-242365453

There is an `--metadata-file` arguments for this:
```
pandoc example.md -o example.pdf --from markdown --template eisvogel --metadata-file=defaults.yaml
```

Many thanks

**Comment by Wandmalfarbe** [comment]
You can also [set the variable directly on the command line with the `-V` option](https://pandoc.org/MANUAL.html#general-writer-options):

```
pandoc example.md -o example.pdf --from markdown --template eisvogel --listings -V logo="logo.pdf"
```
