### ISSUE TITLE
How to insert pages before TOC without including chapter number?

### ISSUE THREAD

**Issue by wxguy** [Wandmalfarbe/pandoc-latex-template#118]
Currently I am using book class to generate pdf file. I need to insert some pages i.e. `acknowledgements` . While there is an option in pandoc to include separate md file with the contents using `--include-before-body=00-acknowledgements.markdown`, the resulting pages contain chapter numbers and TOC has a link to `acknowledgements` like shown below 
![Screenshot from 2019-09-12 11-28-41](https://user-images.githubusercontent.com/9054645/64757706-82332280-d550-11e9-88ff-3389a4fddb7c.png)

Is it possible to include only acknowledgements page (one or more) without including chapter number?

**Comment by Wandmalfarbe** [comment]
> you could try `\section*{Acknowledgements}` or `# Acknowledgements {-}` ...
> 
> i've done something similar in my [pandoc-thesis](https://github.com/cagix/pandoc-thesis) project ...

Yes, that's how you include an unnumbered heading. The second option you mentioned is equivalend with `# Acknowledgements {.unnumbered}` and the preferred way because it is format independent.
