### ISSUE TITLE
Image with caption by default ?

### ISSUE THREAD

**Issue by etnx** [Wandmalfarbe/pandoc-latex-template#119]
Each time I put a picture-link in my .md, the PDF output adds a "Figure N" (N=1,2,3…) string.

I would like to get rid of this "Figure N" thing, especially since I want no caption at all under several pictures.

Is it possible ? Do I have to tweak the template for this ?

**Comment by cagix** [comment]
markdown inline images are translated to `\includegraphics` (cf. https://pandoc.org/MANUAL.html#images) ... you would need to surround the inline image with a `center` environment, i.e. `\begin{center} ![my image](pathtomyimage)\ \end{center}`. however, using a latex environment would stop pandoc from converting the contents of the environment ... 

it seems, you would need to write a short filter and use some custom div like this:

```markdown
:::center
![my image](pathtomyimage)\
:::
```

```lua
-- handling of `::: center ... :::` ... (Div class)
function Div (el)
    if el.classes[1] == "center" then
        return { pandoc.RawBlock("latex", "\\begin{center}"), 
                 el, 
                 pandoc.RawBlock("latex", "\\end{center}") }
    end
end
```

an alternative approach could be to add an option to the inline image like `![my image](pathtomyimage){align=center}\` and to write a lua filter like:

```lua
function Image (el)
    if el.attr.attributes["align"] then
        return { pandoc.RawBlock("latex", "\\begin{" .. el.attr.attributes["align"] .. "}"), 
                 el, 
                 pandoc.RawBlock("latex", "\\end{" .. el.attr.attributes["align"] .. "}") }
end
```

*note*: code is just an idea, not tested!

**Comment by etnx** [comment]
Alas, lua filters work only with Pandoc 2.x and I'm stuck with Pandoc 1.x But I found a workaround:

[](100px-transparent-horizontal.png)\ ![](my-image.png)\

Not very great, because it does not respect style Vs semantic dichotomy, but hey it works.

**Comment by cagix** [comment]
ah, well, this could be implemented in a python filter as well, which should work with pandoc 1.x ...

**Comment by cagix** [comment]
just another filter-free idea: you could define latex macros for `\begin{center}` and `\end{center}` ... like `\newcommand{\startcenter}{\begin{center}}` ... put this definitions in a tex-file, include it via `-H` pandoc option and use your new definitions in your markdown files. since it isn‘t an environment to pandoc anymore, pandoc will happily translate any markdown between your new macros :)

**Comment by etnx** [comment]
Great !

**Comment by Wandmalfarbe** [comment]
> Each time I put a picture-link in my .md, the PDF output adds a "Figure N" (N=1,2,3…) string.
>
> I would like to get rid of this "Figure N" thing, especially since I want no caption at all under several pictures.

You just have to leave the caption empty like so:

```
## Image without Caption

![](image.png)
```

**Comment by cagix** [comment]
good to know ... i assumed, that pandoc would produce an empty caption in this case, like "Figure X:".
