### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by noraj** [Wandmalfarbe/pandoc-latex-template#123]
How can I change the font size of code blocks, verbatim, etc ? Because the font size is larger than the normal text and even a 80 chars line don't fit in one line of code block because the font size is too big.
The default size should be changed in the template and also I would like to know how to change it maybe adding a comment and a variable to be easily changeable.

I only saw this

```latex
\documentclass[
$if(fontsize)$
  $fontsize$,
```

and `basicstyle       = \color{listing-text-color}\linespread{1.0}\small\ttfamily{},` where I tried to change `small` to `scriptsize` without effect in normal mode (works only with --listing).

Anyway `scriptsize` should be the default size for listing and an equivalent should be put for other verbatim renderrer like fvextra.

**Comment by noraj** [comment]
With basicstyle to `\scriptsize` and `--listing` (good size but only with listing package)

![image](https://user-images.githubusercontent.com/16578570/65809114-28f70000-e19a-11e9-807e-2d5921d812dc.png)

With basicstyle to `\small` and `--listing` (too big size and only with listing package)

![image](https://user-images.githubusercontent.com/16578570/65809132-5643ae00-e19a-11e9-970c-bd49313d1487.png)

and default without listing (too big)

![image](https://user-images.githubusercontent.com/16578570/65809142-770c0380-e19a-11e9-95f3-d8d5e2df1edd.png)

**Comment by noraj** [comment]
I achieved it with

```diff
-\DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
+\DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,breakanywhere,fontsize=\scriptsize,numbers=left,commandchars=\\\{\}}
```

Also adding `breakanywhere` and numbering.

![image](https://user-images.githubusercontent.com/16578570/65809574-d409b880-e19e-11e9-9c14-17af793b3fd6.png)

**Comment by noraj** [comment]
PS : this still doesn't apply when a code block doesn't have a valid language name or doesn't have a language specified at all.

![image](https://user-images.githubusercontent.com/16578570/65809598-306cd800-e19f-11e9-85d5-0697061ac29e.png)

**Comment by noraj** [comment]
By running `pandoc --list-highlight-languages` I saw there was a default style.

So by adding the `default` style to a markdown code block instead of none it now display like this.

![image](https://user-images.githubusercontent.com/16578570/65809657-dd475500-e19f-11e9-8953-425f06daab55.png)

I think this should be the default behavior when no style is provided.

**Comment by Wandmalfarbe** [comment]
I added the variable `code-block-font-size` to change the font size for code blocks (verbatim and listings) via the supplied LaTeX command. A value of `\scriptsize` should do the trick:

``````markdown
---
title: "Example PDF"
author: [Author]
date: "2017-02-20"
subject: "Markdown"
keywords: [Markdown, Example]
code-block-font-size: \scriptsize
...

# Java

```java
public class Example implements LoremIpsum {
    public static void map(String[] sortedLeft, Long[] sortedRight, int splitIndex) {
        if(sortedLeft == null || sortedRight == null) {
            System.err.println("Lorem ipsum dolor sit amet");
            var alpha = new Object();
        }
    } // Obscura atque coniuge, per de coniunx
}
```
``````

**Comment by noraj** [comment]
@Wandmalfarbe Thanks you're awesome.
