### ISSUE TITLE
Titlepage background

### ISSUE THREAD

**Issue by giacomomasoncma** [Wandmalfarbe/pandoc-latex-template#128]
I'm having issues using a custom background image for the titlepage of my A4 pdf output.

Here is the image I would like to use:
![bkgd](https://user-images.githubusercontent.com/50147409/66307619-cec60f80-e8fc-11e9-8f91-fd939754e4fc.png)

It gets included correctly if I specify it as a logo in the header:
```
titlepage: true
logo: bkgd.png
```

but not as background
```
titlepage: true
titlepage-background: cmabkgd.png
```

_______________________________________________________________________

Example Rmd file content
```
---
title: Document
author: Me
date: 10 October
titlepage: true
titlepage-background: bkgd.png
logo: logo.png
---

# Document title

Document content
```

**Comment by Wandmalfarbe** [comment]
I can't reproduce this. With the following data it works for me:

```markdown
---
title: "Document"
author: "Me"
date: "10 October"
output: 
  pdf_document: 
    keep_tex: yes
    template: eisvogel
logo: background.png
titlepage: no
titlepage-background: background.png
---

# Document title

Document content
```

Maybe there's an old template file somewhere on your computer? Please run `pandoc --version` from the console and make sure that in the displayed [user data directory](https://pandoc.org/MANUAL.html#option--data-dir) there is no old template file left.

**Comment by giacomomasoncma** [comment]
Thanks! There doesn't seem to be anything in the user data paths that I get below:
![image](https://user-images.githubusercontent.com/50147409/66755678-693fc900-ee90-11e9-8c4d-9874ed036ea6.png)

It's funny that the logo works correctly but not the page background.

I was going to try and print out the latex log using the --log option, but it just prints:
```
[]
```
Anyway, not massively important and also probably a Pandoc problem rather than with the template

**Comment by pianomanfrazier** [comment]
I had the same issue. If you use the template from the github release the background image does not work. I had to make sure to use the current template from the repository.

**Comment by Wandmalfarbe** [comment]
> I had to make sure to use the current template from the repository.

Thank you for pointing it out. The template with background image support is still unreleased and only available from the repository. I should draft a release soon :)

**Comment by giacomomasoncma** [comment]
Thanks, this worked!
