### ISSUE TITLE
Basic example wrong spacing

### ISSUE THREAD

**Issue by klmrdn** [Wandmalfarbe/pandoc-latex-template#129]
I don't know what I'm doing wrong, but when I compiled the examples, in more than one instead of one page, the text only fits on two, because there is too much space before the code.

If I use '--highlight-style' it works okay, only when the '--listings' is specified there is a problem.

Am I doing something wrong? Thanks.

![basic-example](https://user-images.githubusercontent.com/20038870/66415836-0a8bd280-e9ec-11e9-83e3-29ad02a84d0a.png)

**Comment by Wandmalfarbe** [comment]
This is a known issue (see https://github.com/Wandmalfarbe/pandoc-latex-template/issues/91). Please update all your installed LaTeX packages to the latest version. If in doubt you can also delete your LaTeX distribution and do a fresh install. It should solve the spacing issue before and after listings.

**Comment by klmrdn** [comment]
Thank you, will check it out,
