### ISSUE TITLE
Backround Image on all pages

### ISSUE THREAD

**Issue by fsoustra** [Wandmalfarbe/pandoc-latex-template#131]
Hi, 
More a feature than an issue. Would it possible to support background images for all pages as opposed to just the title page? 

Thanks
F

**Comment by evildead** [comment]
I just proposed a pull request regarding this topic.
I implemented this feature on my forked project, and I used it too, because I needed it.
Hope it helps :)

**Comment by Wandmalfarbe** [comment]
The PR from @evildead is now merged. I've added an example on how to use `page-background` in the `examples` folder.
