### ISSUE TITLE
How did you create the backgrounds?

### ISSUE THREAD

**Issue by aggsol** [Wandmalfarbe/pandoc-latex-template#132]
For the artistic impaired like me: Would you mind explaining in simple steps how you created the backgrounds? What tools, PDF format ect. That would be great in the wiki.

**Comment by Wandmalfarbe** [comment]
I use Inkscape when drawing anything vector based. I just import one of the generated PDFs and add objects randomly until I like it. Then I trim every object, delete the text and export to PDF.

<img width="2026" alt="Screenshot 2019-11-13 at 14 20 17" src="https://user-images.githubusercontent.com/17237627/68767471-03766680-0621-11ea-8a3d-69d747aabdc1.png">

I you want to learn more on how to use Inkscape then I highly recommend the [tutorials by Nick Saporito](https://www.youtube.com/channel/UCEQXp_fcqwPcqrzNtWJ1w9w). His tutorial [Mesh Gradient Background](https://www.youtube.com/watch?v=YdqndZ6T3MA) can be used to create a wide variety of other backgrounds for use with Eisvogel.
