### ISSUE TITLE
Error trying to use the eisvogel template

### ISSUE THREAD

**Issue by evildead** [Wandmalfarbe/pandoc-latex-template#133]
Hello,

I tried to use your eisvogel latex template (v1.3.0):
`> pandoc myMDDocument.md -o myPdf.pdf --from markdown --template "./eisvogel.latex" --listings`

and I always get the following error:

```
Error producing PDF.
! pdfTeX error (font expansion): auto expansion is only possible with scalable
fonts.
\AtBegShi@Output ...ipout \box \AtBeginShipoutBox
                                                  \fi \fi
l.643 \begin{lstlisting}

```

what can I do?

**Comment by Wandmalfarbe** [comment]
I assume that you are using Windows because I have experienced the same problem a while back. Please use the suggested solution from [here](https://tex.stackexchange.com/a/392467):

> To solve the problem navigate to `C:\Program Files\MiKTeX 2.9\miktex\bin\x64` and run `updmap.exe`. The program may seem as it hangs for a while, but its probably because it tries to update the whole font tree. This solved the problem for me. After re-compiling everything should work fine.

**Comment by evildead** [comment]
You were completely right man @Wandmalfarbe 
Thank you sooo much, it worked perfectly.

Best Regards
Danilo

**Comment by fkoch-tgm** [comment]
Hey, I have the same Problem:
```bash
pandoc --template eisvogel --listings -f gfm -o mypdf.pdf mymarkdown.md
```

```
Error producing PDF.
! pdfTeX error (font expansion): auto expansion is only possible with scalable 
fonts.
<argument> ...shipout:D \box_use:N \l_shipout_box 
                                                  
l.493 \end{document}
```
But I use manjaro Linux.

**Comment by schumar** [comment]
@fkoch-tgm , I don't think you have the *same* problem -- your error message is different.

I got the same error message as you (running Debian GNU/Linux 11), and the solution was to install the `texlive-full` package (as mentioned in `README.md`) -- for Manjaro, [this guide](https://francopasut.github.io/operating%20systems/Texlive-Manjaro/) might help.
