### ISSUE TITLE
Different page margins w/o titlepage

### ISSUE THREAD

**Issue by gitkeeper** [Wandmalfarbe/pandoc-latex-template#135]
When I compile a PDF **without** a titlepage, the page margins on all pages are huge, especially on the bottom. Is this behaviour normal or did I overlook something?

Page margins are equal and look good with:
```
---
titlepage: true
...

# Readme
(...)
```

Page margins are way off with the titlepage set to false. There's a lot more whitespace on the bottom, left and right on each page:
```
---
titlepage: false
...

# Readme
(...)
```

I execute pandoc as follows:
```
pandoc Readme.md -f markdown --template eisvogel --listings -o Readme.pdf
```

PDF files for reference:
[Readme1.pdf](https://github.com/Wandmalfarbe/pandoc-latex-template/files/3903225/Readme1.pdf)
[Readme2.pdf](https://github.com/Wandmalfarbe/pandoc-latex-template/files/3903226/Readme2.pdf)

**Comment by Wandmalfarbe** [comment]
Thank you for submitting this Issue. It should be fixed now on the `master` branch.
