### ISSUE TITLE
Changing footer and header to another YAML variable

### ISSUE THREAD

**Issue by abers** [Wandmalfarbe/pandoc-latex-template#136]
Apologies as this is likely an extremely noob question but I couldn't find the answering Googling. Is it possible using the header and foot variables to specify other variables set in the YAML.

For example, footer-left defaults to author. What would I need to include in the YAML so that it uses the subtitle? 

For example -

```
---
title: "Some title"
subtitle: "Subtitle"
footer-left: subtitle
---
```

**Comment by cagix** [comment]
well, lines 821 ff in `eisvogel.tex` say:

```tex
  \lhead[$if(header-right)$$header-right$$else$$date$$endif$]{$if(header-left)$$header-left$$else$$title$$endif$}
  \chead[$if(header-center)$$header-center$$else$$endif$]{$if(header-center)$$header-center$$else$$endif$}
  \rhead[$if(header-left)$$header-left$$else$$title$$endif$]{$if(header-right)$$header-right$$else$$date$$endif$}
  \lfoot[$if(footer-right)$$footer-right$$else$\thepage$endif$]{$if(footer-left)$$footer-left$$else$$for(author)$$author$$sep$, $endfor$$endif$}
  \cfoot[$if(footer-center)$$footer-center$$else$$endif$]{$if(footer-center)$$footer-center$$else$$endif$}
  \rfoot[$if(footer-left)$$footer-left$$else$$for(author)$$author$$sep$, $endfor$$endif$]{$if(footer-right)$$footer-right$$else$\thepage$endif$}
```

so you can use `header-right` ... `footer-left`. however, afaik there is no substitution mechanism for metadata variables, so you would have to duplicate entries like so:
```yaml
---
title: "Some title"
subtitle: "Subtitle"
footer-left: "Subtitle"
---
```

an alternative would be to modify the template, i.e. to change the definitions to `\rfoot[$if(footer-left)$$subtitle$$else$$for(author)$$author$$sep$, $endfor$$endif$]{$if(footer-right)$$footer-right$$else$\thepage$endif$}`

**Comment by abers** [comment]
Thanks. I am wondering if it would be possible to add substitution by modifying the template or whether this is a pandoc limitation?

**Comment by cagix** [comment]
afaik this is a pandoc limitation ...

**Comment by cagix** [comment]
however, maybe you could process the document (or parts of it) twice, cf. https://github.com/jgm/pandoc/wiki/Pandoc-Tricks#template-snippet

```
pandoc --template=template_snippet.tex document.md -o processed_snippet
pandoc ... -H processed_snippet document.md -o document.<toFormat>
```

**Comment by cagix** [comment]
or maybe deploy a little lua filter, which replaces the metadatavariable `footer-left` with the actual value of the metadatavariable `subtitle` (https://pandoc.org/lua-filters.html)

**Comment by Wandmalfarbe** [comment]
@cagix Thank you for answering the issue! Something like that

```
---
title: "Some title"
subtitle: "This is My Subtitle"
footer-left: "$subtitle$"
---
```

is not possible because the text of `footer-left` is not interpreted as a template. You could however duplicate the text:

```
---
title: "Some title"
subtitle: "This is My Very Cool Subtitle"
footer-left: "This is My Very Cool Subtitle"
---
```
