### ISSUE TITLE
Image doesn't display

### ISSUE THREAD

**Issue by Gowa2017** [Wandmalfarbe/pandoc-latex-template#139]
Only caption is displayed,help me.
![image](https://user-images.githubusercontent.com/33367355/72136416-bc5be600-33c3-11ea-8deb-66b9142c9b96.png)

**Comment by Wandmalfarbe** [comment]
You likely specified the wrong path to the image.

```
![This is the caption.](path/to/image.png)
```

The path needs to be relative to where your document is located. Here's an example:

```
.
├── document.md
└── images/
    └── flowers.png
```

Inside `document.md` the image should be embedded like this:

```
![This is the caption.](images/flowers.png)
```

It is also possible that the image you provided is not recognized by LaTeX. You can only embed PDF, PNG and JPG images.

Please provide additional information such as the full output log (obtained with the flag `--verbose`) or the source document.
