### ISSUE TITLE
Problems with Chinese documents

### ISSUE THREAD

**Issue by ZhangYikaii** [Wandmalfarbe/pandoc-latex-template#140]
Although I used `--latex-engine=xelatex`, I still get garbled characters when converting Chinese files.

Thank you anyway

**Comment by Wandmalfarbe** [comment]
You have to specify the CJK font with [the option `CJKmainfont`](https://pandoc.org/MANUAL.html#fonts):

```
pandoc --template eisvogel.tex chinese.md -o chinese.pdf --pdf-engine xelatex -V CJKmainfont="HiraginoSans-W4"
```

You can use any CJK font that is installed on your system. I used `HiraginoSans` because it is preinstalled on macOS. I've added an example `chinese` to the `examples` folder.

**Comment by scottming** [comment]
This command `pandoc chinese.md -o chinese.pdf --from markdown --template eisvogel --listings --pdf-engine=xelatex  -V CJKmainfont="HiraginoSans-W4"` not work for 'simplified Chinese'

You could use this example to recur the problem:
```
---
title: "価备手述改陆夜数木田了転由。"
author: [作者日期]
date: "2019-01-10"
subject: "Markdown"
keywords: [Markdown, Example]
...

# 阵委百三秋康経重示面合雪减背井足府迷根间。

阵委百三秋康経重示面合雪减背井足府迷根间。米式十良提马纪研园要中募用刊。考稿协中写万捜寄三诚女文惑応担。动忍负阵表要回厳盛质属全任。意渡稿针当京注合在成唱皇月诸感丘売。业暮题武同海変公饭伝习真质期込者。読性闻点社质求库势応系飞。読有约求不政球県台却観展明来连使。暗双属场证北日増吉望団私录写日奈惑纸。

赏方広选付疑京将主豊祉歳兆。亮行灾视民信轩全太当刑际大。设纸校系颜実困讲将用求年作。禁査调线无闻铜案性约会有整兄名城敬番棋。催题趣蔵今権全演権専治整。记査调埼毎断読犬石川年実作问情设情経。地面観参軽地多爱提帯瀬面侧天侧。価备手述改陆夜数木田了転由。上転为护吾载何研防著取足调出声的与歯。

## 参街能业南达伊市无百兆无闻手覧常努団他。

参街能业南达伊市无百兆无闻手覧常努団他。応临覧処面板施盛会同交展安期。善无継东约知纸地言展掲世起都幕纸仕。配稿理第心酸知月胜庭上図真全。本顕品毎信稿蓄秀神池课道。空米打资级油周报白受支写住文科権初航逮政。売打込箕长陈雪択选男真庭。改取确育迎田袴者豊尾京毎景终彦思。意试役能五子込宙転知校细。内速排索医林経一応系古测辺水。

纹正介市及早拒木霊记済复治中。了岐都援盛手価民选覧必庭温背木済円力治。年生算纯投器小市系统出字明稚吃部秘集。背伝歳适虫解无集园意明属赏方社件。公绍情高无主考全度监授掲。三退新田面封一基会功康売详夜増义芸。特积夫纪北赤子演载识颜产済再测质。新岐张年読原体畑住郎门当合止吹士天意藤。明延立派购新政医士定速农。

神図先名当揃存工纸広渡民晩记各面得続告増。将枝素実更造藤胞界投健记室申张讲诉。店裁山党手政者校训会清终定浪案。普大的比将响认経変度与合兄退景意経。歌池京割覧制断訳载割写载女作想用魂覚申。舞夜负亡古特在事准催进不全先自代上业后者。学上育手系真最芋本代定作供下能読分。

- 汁酬英性向竹室比著给稿刻学年机稿生写。投面记偏回必写际著危女竞林思。対事管现马打能夜月顾身最恵共谷盟社必出。事退问更理并里少切写禁権丁金提限最写求。者打记舎作马研作辞家地子无远者情岛。诸井训団取転燃大広応毎断略并。力持极业育権者住今展线际玉。集政谦期伝変争一他拉方海话连委下混必。囲渡园早位形量英酒椅食始発児政。
- 年京船装街论初维器送遂考都连。携访后细断点洋再说月间必道休光事筑河。闻直电原竹銭报発兴埼校球米口暮定奨重芸闻。京和使検闻服运加航认着着真技事実。弘断机试势感金换稼治山谷皇真人肥雾。夜需崎影书属叶総登抜见発养内日现际园。场小行评歳映彻浸力政中募暮日朝金子武东。映申地换方无次记暮动练供事惑部意喜半戦坛。
- 胜技枝図辞决受温见会図休自意少帰质者栄。务単时干典盟园先入贩江纪闻択色务。逮人覇品努博関复际部给体寛明理。限袖住教催広州系响体回接决治过银。世提応枝录少说営援纸远勤灾宿。试电重捕切谱练治真戦将东。在最真休治义地杉调掲参亲平。必整能怒哲希存雪注気付终表転県横队早。覧教夕彻八学然害犬米无调亿立図平受受位编。

昌手挨一主要入削禁図送无高慕収后毎投业。感心台観道际町存更団打目今。生记投报重东点回际护高田独东。球野技検业大芸闻共最集飞禁。无黄手著凯缩产総智幕配示。名旧合提丼畿幅间任问场投悪変団。津地全真罪禁友容崩図新足连问完。域勲市录関写気意伤遣米安极汉。个疑调尾陆能案相浮接格校田新本下能。日銭信茶冈実缔缲先分読独娘制商损真情。
```

@Wandmalfarbe

**Comment by scottming** [comment]
I'm stupid.

If I use "PingFang SC" instead of "HiraginoSans-W4", that worked.

**Comment by icuxika** [comment]
> You have to specify the CJK font with [the option `CJKmainfont`](https://pandoc.org/MANUAL.html#fonts):
> 
> ```
> pandoc --template eisvogel.tex chinese.md -o chinese.pdf --pdf-engine xelatex -V CJKmainfont="HiraginoSans-W4"
> ```
> 
> You can use any CJK font that is installed on your system. I used `HiraginoSans` because it is preinstalled on macOS. I've added an example `chinese` to the `examples` folder.

This reply helped me solve the problem, thanks
