### ISSUE TITLE
File `footnotebackref.sty' not found.

### ISSUE THREAD

**Issue by pres-luca** [Wandmalfarbe/pandoc-latex-template#141]
I get this error when I try to create the PDF. I guess I'm missing some kind of Latex extension or something but I could not find what I needed to install with a quick ddg search.
Both texlive-biin and texlive-core are installed on my manjaro setup if that helps any.

**Comment by Wandmalfarbe** [comment]
You need the additional package `footnotebackref` (and possibly some more). Install missing packages with `tlmgr install <package>`.

## Texlive

Eisvogel requires a full texlive distribution that can be installed by running `apt-get install texlive-full` in the terminal. Because `texlive-full` is very large (about 5 Gigabytes) you can also install the smaller texlive bundles and add any missing packages manually.

You need to install `texlive-latex-extra`. With `texlive-latex-extra` you also need to install these packages manually:

```sh
adjustbox background bidi csquotes footmisc footnotebackref fvextra mdframed pagecolor 
sourcecodepro sourcesanspro titling ulem upquote xurl letltxmacro zref everypage framed 
collectbox xecjk filehook unicode-math ucharcat pagecolor babel-german ly1 mweights 
sourcecodepro sourcesanspro mdframed needspace fvextra footmisc footnotebackref 
background
```

Install them with 

```sh
tlmgt install adjustbox background bidi csquotes footmisc footnotebackref fvextra mdframed pagecolor sourcecodepro sourcesanspro titling ulem upquote xurl letltxmacro zref everypage framed collectbox xecjk filehook unicode-math ucharcat pagecolor babel-german ly1 mweights sourcecodepro sourcesanspro mdframed needspace fvextra footmisc footnotebackref background
```

Additional information about the different texlive packages can be found at this TeX-StackExchange answer: <https://tex.stackexchange.com/a/504566>

## A Note on MiKTeX

If you don't want to install all missing packages manually [MiKTeX might be an alternative](https://miktex.org/howto/miktex-console).

> MiKTeX has the ability to automatically install missing packages.
> You can turn this feature on or off. And you can let MiKTeX ask you each time a package has to be installed:
> 
> - Click `Settings` to navigate to the settings page.
> - Click the `General` tab.
> - Click one of the radio buttons:
>     - `Ask me`
>     - `Always install missing packages on-the-fly`
>     - `Never install missing packages on-the-fly`

**Comment by alexellis** [comment]
I also ran into this, I wonder if a message on the README would help folks like us?

**Comment by alexellis** [comment]
I installed Pandoc and a LaTex compiler via brew, do you have any instructions for MacOS users? The above assumes a Linux distro.

**Comment by 1modm** [comment]
In MacOS I fixed the issue with footnotebackref installing mactex:
$ brew remove basictex
$ brew cask install mactex

**Comment by whldk** [comment]
my system is centos7 .... so yum install  xxx  ,  no no no ,  you  say  for me  haw do you do ?

**Comment by 1modm** [comment]
@whldk I suppose `sudo yum install texlive-*` or manually: https://www.tug.org/texlive/quickinstall.html

**Comment by emiridbest** [comment]
i solved it by installing full version of latex 
```shell
sudo apt-get install texlive-full

```

**Comment by Parth-Sharma-tonchi** [comment]
@Wandmalfarbe, I got this error while using this command, what should I do : 
```$ sudo tlmgr install adjustbox babel-german background bidi collectbox csquotes everypage filehook footmisc footnotebackref framed fvextra letltxmacro ly1 mdframed mweights needspace pagecolor sourcecodepro sourcesanspro titling ucharcat ulem unicode-math upquote xecjk xurl zref
[sudo] password for parth:           
(running on Debian, switching to user mode!)
(see /usr/share/doc/texlive-base/README.tlmgr-on-Debian.md)

tlmgr: Local TeX Live (2021) is older than remote repository (2024).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
```

**Comment by FalseGenius** [comment]
@Parth-Sharma-tonchi 

> `[sudo] password for parth:           
(running on Debian, switching to user mode!)
(see /usr/share/doc/texlive-base/README.tlmgr-on-Debian.md)

tlmgr: Local TeX Live (2021) is older than remote repository (2024).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.`

Any luck with this?

**Comment by adnanhamidbeigh** [comment]
Exactly @0xfalafel 🙌
