### ISSUE TITLE
Problem with national characters in author's name on the title page

### ISSUE THREAD

**Issue by Tomas-Jankovic** [Wandmalfarbe/pandoc-latex-template#15]
Hi,

I have in my name slovak national characters. When I use my name as author's name  there is an issue on the title page. When I have removed 'uppercase' method on line 644 everythings seems to me OK. But it be better if uppercase method works with national characters as well.

This is the line:
```
{\Large \textsf{\uppercase{$for(author)$$author$$sep$, $endfor$}}
```

[test.md.gz](https://github.com/Wandmalfarbe/pandoc-latex-template/files/1425018/test.md.gz)
[test-without_uppercase.pdf](https://github.com/Wandmalfarbe/pandoc-latex-template/files/1425019/test-without_uppercase.pdf)
[test-with_uppercase.pdf](https://github.com/Wandmalfarbe/pandoc-latex-template/files/1425020/test-with_uppercase.pdf)

**Comment by Wandmalfarbe** [comment]
So apparently the TeX command `\uppercase` [should not be used anymore](http://www.tex.ac.uk/FAQ-casechange.html). I replaced the command with `\MakeUppercase` which appears to work fine.

**Comment by Tomas-Jankovic** [comment]
Thank you very much :)
