### ISSUE TITLE
Error with double carets in listings code block

### ISSUE THREAD

**Issue by jsinkers** [Wandmalfarbe/pandoc-latex-template#157]
Loving this template so far but ran into this issue with inline double carets `^^` - took me quite a while to figure out this was the problem.  Was able to work around it by separating into two separate in-line blocks, but I'm guessing that this isn't intended behaviour.

Running `pandoc test.md -o test.pdf --from markdown --template eisvogel.tex --listings` with
`test.md`:
```
`^^`
```
produces:
```
Error producing PDF.
! File ended while scanning use of \lst@temp.
<inserted text> 
                \par 
<*> /tmp/tex2pdf.-123e5503f3b3824b/input.tex
                                             
Here is how much of TeX's memory you used:
 28660 strings out of 494923
 487490 string characters out of 6180742
 718748 words of memory out of 5000000
 31684 multiletter control sequences out of 15000+600000
 552952 words of font info for 32 fonts, out of 8000000 for 9000
 14 hyphenation exceptions out of 8191
 49i,4n,95p,10561b,1220s stack positions out of 5000i,500n,10000p,200000b,80000s

!  ==> Fatal error occurred, no output PDF file produced!
```

I'm assuming it's to do with the syntax highlighting, because it ran fine without `--listings`.

**Comment by Wandmalfarbe** [comment]
Fixed upstream in commit https://github.com/jgm/pandoc/commit/9d0506e4047f797a0672d7767830b59f1710d191 which is available with [pandoc 2.10](https://github.com/jgm/pandoc/releases).
