### ISSUE TITLE
Smart quotes

### ISSUE THREAD

**Issue by karkraeg** [Wandmalfarbe/pandoc-latex-template#158]
How can I enable German Quotes („“) instead of  “” ? My YAML-frontmatter has `lang: "de"` included and I tried pandoc with the option `-V lang=de` but the quotes are always the english ones.

**Comment by amaridev** [comment]
I wondered myself and didn't figure it out. I used a plugin for Visual Code to replace all quotes with smart quotes.

**Comment by Wandmalfarbe** [comment]
Smart quotes for languages other than English are not directly supported by pandoc. Please see this discussion on the issue https://github.com/jgm/pandoc/issues/2620. Some mentioned solutions are:

- Write your Input file with the proper quotes that you want to appear in the output file.
- Use smart quotes in your input file and replace them programmatically (e.g. with `sed` or some other tool).
- Use a pandoc filter.

    > @odkr wrote a great Lua filter to handle this problem:
    > https://github.com/odkr/pandoc-quotes.lua. It is now also available as part of the pandoc lua-filters collection: https://github.com/pandoc/lua-filters/tree/master/pandoc-quotes.lua
