### ISSUE TITLE
Relocate date in the header and footer

### ISSUE THREAD

**Issue by microraptor** [Wandmalfarbe/pandoc-latex-template#163]
Using the metadata variables `header-left`, `footer-right`, etc. to assign `\\thetitle`, `\\thepage` and `\\theauthor` works flawlessly. However, with `\\thedate` I get this error:

> Error producing PDF.
> ! Undefined control sequence.
> \f@nch@olf ->\thedate 
>                       \strut 
> l.319   S

It is the same with using `\thetitle`, `\thepage` and `\theauthor` inside the body. Which works fine, but not `\thedate`. Is it not possible to reference the date?

**Comment by Wandmalfarbe** [comment]
This should be fixed now. Thank you for reporting this issue.

**Comment by brenocss** [comment]
@Wandmalfarbe would be great if exists \\thesubtitle
