### ISSUE TITLE
Unable to display pictures with Eisvogel

### ISSUE THREAD

**Issue by Etturaz** [Wandmalfarbe/pandoc-latex-template#165]
Already checked the similar question posed by issue #139 which doesn't solve my problem.
In my case, if I use the _deafault.latex_  template I can see the images on the converted document, none if use _eisvogel.latex_.
I' ve tried with *.png, *.jpg, *.pdf and even *.svg which works under the _deafault.latex_.
I use:
- XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/Arch Linux)
- pandoc 2.9.2.1
- eisvogel.template downloaded yesterday, 2020/04/02.
I' ve tried running the script with pdfLatex and it works, not if select the option **--pdf-engine=xelatex**.
Any idea?

P.S.: sorry, I' ve forgotten to say that the floats are there, but it stays white. Even the captions are not shown.

**Comment by Wandmalfarbe** [comment]
Could you provide a full example (like a folder structure that you just zip)? That helps me to understand the problem. Also, the full pandoc log is really helpful.

**Comment by wtraylor** [comment]
I had the same issue that PNG figures would not always be rendered.
Merge #164 has fixed it for me by replacing `\usepackage{graphicx}` with `\usepackage{graphicx,grffile}`.

**Comment by Penguin-P** [comment]
remove graphicx dependency #164 by replacing `\usepackage{graphicx,grffile}` with `\usepackage{graphicx}` worked for me.

**Comment by Wandmalfarbe** [comment]
This should be resolved. If there are still any problems don't hesitate to open a new issue.

**Comment by lrmatheen** [comment]
I am able to apply eisvogel template to a md file where there are no images. md file with images are not converted to pdf. Attaching my zipped folder here.
Error show is:
Error producing PDF.
! Undefined control sequence.
l.404 \pandocbounded
[experiment.zip](https://github.com/user-attachments/files/16484435/experiment.zip)
[experiment.zip](https://github.com/user-attachments/files/16484436/experiment.zip)

**Comment by Wandmalfarbe** [comment]
@lrmatheen The issue you describe is reported in #391 and fixed in [version 2.5.0](https://github.com/Wandmalfarbe/pandoc-latex-template/releases/tag/v2.5.0) of the Eisvogel template.
