### ISSUE TITLE
How do I set the fenced code font size smaller?

### ISSUE THREAD

**Issue by youzhonghui** [Wandmalfarbe/pandoc-latex-template#17]
Awesome job. This template do me a huge favor. I want to change the highlight code area smaller font size. Can anyone tell me how to do it?

**Comment by Wandmalfarbe** [comment]
Thank you for the praise!

When you use `listings` for syntax-highlighting (passing the flag `--listings` on the command line), then you just have to replace the `\small` in [line 147](https://github.com/Wandmalfarbe/pandoc-latex-template/blob/master/eisvogel.tex#L547) by a font size of your choice. You can use `\tiny`, `\scriptsize`, `\footnotesize`, `\small`, `\normalsize`, `\large`, `\Large`, `\LARGE`, `\huge` and `\Huge`.

[This StackExchange thread](https://tex.stackexchange.com/questions/24599/what-point-pt-font-size-are-large-etc) has a nice overview of the font sizes.

**Comment by youzhonghui** [comment]
That's Work! Many thanks.

**Comment by Wandmalfarbe** [comment]
I just added the variable `code-block-font-size` to change the font size for code blocks via the supplied LaTeX command:

> The available values are `\tiny`, `\scriptsize`, `\footnotesize`, `\small`, `\normalsize`, `\large`, `\Large`, `\LARGE`, `\huge` and `\Huge`. This option will change the font size for default code blocks using the verbatim environment and for code blocks generated with listings.

One can use it like this:

````markdown
---
title: "Example PDF"
author: [Author]
date: "2017-02-20"
subject: "Markdown"
keywords: [Markdown, Example]
code-block-font-size: \tiny
...

# Java

```java
public class Example implements LoremIpsum {
    public static void map(String[] sortedLeft, Long[] sortedRight, int splitIndex) {
        if(sortedLeft == null || sortedRight == null) {
            System.err.println("Lorem ipsum dolor sit amet");
            var alpha = new Object();
        }
    } // Obscura atque coniuge, per de coniunx
}
```
````
