### ISSUE TITLE
Euro currency symbol in Markdown file is translated to \euro instead of \texteuro

### ISSUE THREAD

**Issue by topofocus** [Wandmalfarbe/pandoc-latex-template#172]
Using the standard pdflatex option, the € symbol is somehow translated.
Latex knows how to operate with UTF8 Symbols, including the €, £, etc. 

Is it possible, to omit the translation of special characters?

If not, how to change \euro to \texteuro\/  ?

Thanks

hartmut

**Comment by topofocus** [comment]
If just learned, that Ubuntu 18.04 still installs Pandoc 1.19.
After manually installing the most  recent deb-package, anything works fine

**Comment by AvverbioPronome** [comment]
This should not be an issue with `\usepackage[utf8]{inputenc}`, there would be no reason to translate the euro symbol to anything.
