### ISSUE TITLE
Version-string-less archive in release files

### ISSUE THREAD

**Issue by alexpovel** [Wandmalfarbe/pandoc-latex-template#175]
I am currently trying to embed this template in a CI pipeline. To get the latest release, the following code works:

```bash
PANDOC_TEMPLATE_URL=$(\
    curl -s https://api.github.com/repos/Wandmalfarbe/pandoc-latex-template/releases/latest | \
    grep "browser_download_url.*\.tar\.gz" | \
    cut -d \" -f 4
)
# Download archive
wget $PANDOC_TEMPLATE_URL
# Unpack single file
tar -xf Eisvogel*.tar.gz eisvogel.tex
# Change that file's suffix to .latex
mv eisvogel.tex eisvogel.latex
```

This is a bit verbose of course.
The issue has been discussed [here](https://stackoverflow.com/a/54836319/11477374): on GitHub, it is now possible to have a link like <https://github.com/Wandmalfarbe/pandoc-latex-template/releases/latest/download/package.zip>.

But of course, `package.zip` does not exist in the latest [Release assets](https://github.com/Wandmalfarbe/pandoc-latex-template/releases/tag/v1.4.0).

Would it be possible to have a generically named archive there, like `eisvogel.tar.gz`, that always resolves fine? It could sit in parallel to the rest of the assets.

Navigating automatically to the latest release is nice, but not usable when the assets themselves contain version strings.
This change would also allow neat usage of Docker's `ADD`.

**Comment by Wandmalfarbe** [comment]
You can now download the latest release with the URLs
- <https://github.com/Wandmalfarbe/pandoc-latex-template/releases/latest/download/Eisvogel.zip> or
- https://github.com/Wandmalfarbe/pandoc-latex-template/releases/latest/download/Eisvogel.tar.gz
