### ISSUE TITLE
Add colorlinks config option to README

### ISSUE THREAD

**Issue by Lednerb** [Wandmalfarbe/pandoc-latex-template#177]
Given the following example:

![image](https://user-images.githubusercontent.com/2056876/83358279-afd82a00-a372-11ea-8fb7-e3fca0a3bc3a.png)

The marked `LINK` is acutally a hyperlink, but it's not visible in the rendered pdf.

Maybe the style can be adjusted for better visibility.

**Comment by microraptor** [comment]
Have you used `colorlinks: true` in the YAML metadata?

**Comment by Lednerb** [comment]
@microraptor thanks for the feedback, with enabled `colorlinks: true` everythings works as expected.

Maybe this option can be added to the `README.md` for other users in the future?

**Comment by Wandmalfarbe** [comment]
This option is already documented in the pandoc manual. I only document additional options that are not part of the pandoc default template.

**Comment by joelpurra** [comment]
For others digging around, here's the relevant section for `colorlinks` in the pandoc manual: https://pandoc.org/MANUAL.html#links
