### ISSUE TITLE
Prevent image stretching

### ISSUE THREAD

**Issue by Lednerb** [Wandmalfarbe/pandoc-latex-template#178]
Hello again

Using markdown for writing my report I've included images.

However small images get stretched over the full page width using this command:

```
pandoc src.md -o out.pdf \
  --from markdown+yaml_metadata_block+raw_html \
  --template eisvogel \
  --table-of-contents \
  --toc-depth 6 \
  --top-level-division=chapter \
  --highlight-style zenburn \
  --pdf-engine xelatex
```

Image is included with:

```md
![](/full/path/to/image-20200530001039454.png)
```

However, images that would overflow the page are reduced correctly to the site's width.
How can I disable stretching the smaller ones?

**Comment by cagix** [comment]
i'd guess that this is due to the definition in line 368 ff:

```latex
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
```

what happens if you specify the dimensions directly, like `![](/full/path/to/image-20200530001039454.png){width="100%"}`?

**Comment by Lednerb** [comment]
This produces the same output.
I assume that's caused by the `100%` referencing the full page width.

However setting the `{width="10cm"}` allow me to adjust the size and it also keeps the ratio.
Additionally the image needs to be centered by additional attributes / commands.

Maybe this can be streamlined for a better user experience?

However, the lines you are referencing are within an `$if(graphics)$` blocks.
If I comment out the `if` and `endif` line to always use this settings, compiling does not work:

```
Error producing PDF.
! Package keyval Error: width undefined.

See the keyval package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.169 ...xwidth,height=\maxheight,keepaspectratio}
```

**Comment by cagix** [comment]
hmmm, that reminds me of generating beamer slides with pandoc, where the same behaviour can be observed.

the lines mentioned are inherited from the original latex template in pandoc. maybe it's an upstream issue?

**Comment by Wandmalfarbe** [comment]
> However small images get stretched over the full page width using this command:

I can not reproduce this behavior. When I include a small image it gets embedded without stretching:

<img width="704" alt="Screenshot 2020-06-02 at 23 15 48" src="https://user-images.githubusercontent.com/17237627/83570962-346ba980-a527-11ea-971b-fd35eff9c8ca.png">

[issue-178-image-stretching.zip](https://github.com/Wandmalfarbe/pandoc-latex-template/files/4719747/issue-178-image-stretching.zip)

> i'd guess that this is due to the definition in line 368 ff:
> 
> ```latex
> % Scale images if necessary, so that they will not overflow the page
> % margins by default, and it is still possible to overwrite the defaults
> % using explicit options in \includegraphics[width, height, ...]{}
> \setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
> ```

Yes, that is the code to resize images. In full, it looks like this:

```latex
$if(graphics)$
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
$endif$
```

> the lines mentioned are inherited from the original latex template in pandoc. maybe it's an upstream issue?

It looks like it. If I remember correctly pandoc takes things like DPI into account when embedding images. Maybe your image has embedded dpi information? Can you provide the image in question and a minimal example in a ZIP file?

You may want to report it upstream in the pandoc issue tracker (https://github.com/jgm/pandoc/issues).
