### ISSUE TITLE
How to ref a table/ figure?

### ISSUE THREAD

**Issue by normenmueller** [Wandmalfarbe/pandoc-latex-template#189]
Is there any syntax how to give a table/ figure a label and later on reference it? Adding filter `pandoc-crossref` results in the following error:

```
! Undefined control sequence.
<argument> \passthrough
                        {\lstinline !pandoc-latex-environments!}
l.349 ...h{\lstinline!pandoc-latex-environments!}}
```

**Comment by cagix** [comment]
since LaTeX is used as the backend, you could use the good old tex commands: `\label{my:label}` to set a label `my:label` and `\ref{my:label}` to reference a label `my:label`...

**Comment by starlocke** [comment]
Example markdown, for reference:

```markdown
![HTTP 100: Continue. \label{fig:http_100}](https://http.cat/100.jpg)

In Figure \ref{fig:http_100}, all is well and we may continue.
```

**Comment by cunhapaulo** [comment]
Use this:

![Alt text \label{mylabel}][image]
See figure \ref{mylabel}.
