### ISSUE TITLE
Error on footnotes

### ISSUE THREAD

**Issue by manelio** [Wandmalfarbe/pandoc-latex-template#19]
It seems there is some problem with blank lines on footnotes:

This code from MANUAL.txt:

    [^subtitle]: To make `subtitle` work with other LaTeX
        document classes, you can add the following to `header-includes`:

            \providecommand{\subtitle}[1]{%
              \usepackage{titling}
              \posttitle{%
                \par\large#1\end{center}}
            }

Throws an error:

    Runaway argument?
    \providecommand {\subtitle }[1]{\usepackage {titling} \posttitle {
    ! Paragraph ended before \FV@BeginScanning was complete.
    <to be read again> 
                      \par 
    l.1457 }

But if I remove the first white line:

    [^subtitle]: To make `subtitle` work with other LaTeX
        document classes, you can add the following to `header-includes`:
            \providecommand{\subtitle}[1]{%
              \usepackage{titling}
              \posttitle{%
                \par\large#1\end{center}}
            }

All goes well.

**Comment by Wandmalfarbe** [comment]
@manelio I regularly try to compile the markdown from here when I change code in my template and now it works. I don't know what change fixed this issue, but the following code does compile without error:

```
# Lorem ipsum dolor sit amet

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt[^subtitle] ut labore et dolore magna aliquyam erat, sed diam voluptua. 

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt^[At vero eos et accusam et justo duo dolores et ea rebum.] ut labore et dolore magna aliquyam erat, sed diam voluptua.

## Takimata sanctus est

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

[^subtitle]: To make `subtitle` work with other LaTeX
    document classes, you can add the following to `header-includes`:

        \providecommand{\subtitle}[1]{%
          \usepackage{titling}
          \posttitle{%
            \par\large#1\end{center}}
        }
```

```
/usr/local/bin/pandoc -o footnotes.pdf footnotes.md -V colorlinks=true -V lang=de --from markdown+footnotes --template "eisvogel" --highlight-style kate --listings --pdf-engine=xelatex --number-sections
```

I hope the issue is fixed for you and can be closed. Sorry that I didn't respond earlier, but I simply had nothing to add to this issue.
