### ISSUE TITLE
Page background opacity not working

### ISSUE THREAD

**Issue by intermezzio** [Wandmalfarbe/pandoc-latex-template#190]
While I can select a custom page background, the background is always 100% opaque whether or not I pass an argument for page-background opacity. A minimal example of this is as shown:

```md
 ---
 title: "Title Here"
 author: Author
 page-background: "backgrounds/background5.pdf"
 page-background-opacity: 0.5
 ---
 # Content here
 ```
I installed texlive latex extra and the packages listed on the readme, and I use xelatex to write to pdf. If it helps, I am running this on Manjaro Linux with KDE.

**Comment by intermezzio** [comment]
EDIT: although changing the pdf engine to the default setting threw errors, using the lualatex engine fixed this problem.

**Comment by porl** [comment]
Using latest release (2.5.0) I have this same issue - page backgrounds are full opacity no matter the setting when using `--pdf-engine=xelatex` but work correctly with `--pdf-engine=lualatex`.
