### ISSUE TITLE
How to get the H4 and H5 menus in .PDF ?

### ISSUE THREAD

**Issue by LeaKitty** [Wandmalfarbe/pandoc-latex-template#191]
Hello,

When converting to PDF I noticed that the H4 and H5 menus are not taken into account.

So I searched for a similar problem here and came across this : 

- [Too many HEADING levels are not well rendered](https://github.com/Wandmalfarbe/pandoc-latex-template/issues/162)
- [block-headings](https://pandoc.org/MANUAL.html#variables-for-latex)

The concern is that I don't see how it works, could you please indicate the steps to follow.

**Comment by Wandmalfarbe** [comment]
You need to [set `--toc-depth` to the section level](https://pandoc.org/MANUAL.html#option--toc-depth) that will be included in the table of contents. You are not seeing entries in the TOC for the H4 and H5 because the default value is 3.
