### ISSUE TITLE
Header and footer adjustments ?

### ISSUE THREAD

**Issue by LeaKitty** [Wandmalfarbe/pandoc-latex-template#194]
Hello, 

is it possible to adjust the header and footer ?

For example, I would like the header to be higher and the footer to be lower.

**Comment by s-maurice** [comment]
Perhaps try adjust the margins?
https://pandoc.org/faqs.html#collapse-how-do-i-change-the-margins-in-pdf-output

**Comment by LeaKitty** [comment]
Oh great, thank you very much @s-maurice ;)
