### ISSUE TITLE
How can I disable page style on specific pages/sections?

### ISSUE THREAD

**Issue by pykong** [Wandmalfarbe/pandoc-latex-template#196]
I'd like to have the pages for my bibliography and code listings both at the end of the document to have no header or footer.
I could not achieve this via including the LaTeX command `\thispagestyle{empty}` at the regarding pages. Normal pages should keep their header and footer.

Is there any easy way to achieve this using this splendid template?

**Comment by Wandmalfarbe** [comment]
> I'd like to have the pages for my bibliography and code listings both at the end of the document to have no header or footer.
> I could not achieve this via including the LaTeX command `\thispagestyle{empty}` at the regarding pages. Normal pages should keep their header and footer.
> 
> Is there any easy way to achieve this using this splendid template?

This is currently not possible with the Eisvogel template. However, I believe one can insert `\thispagestyle{empty}` to remove the header and footer (this might need some fiddling). An option to disable header and footer on certain pages will not be included.
