### ISSUE TITLE
I am trying to have \midrule between each table rule, I am not succeeding. 

### ISSUE THREAD

**Issue by AvverbioPronome** [Wandmalfarbe/pandoc-latex-template#197]
This isn't probably eisvogel-related, but I could appreciate the input.

I tried doing: 

- `\newcommand{\tabularnewline}{\tabularnewline\midrule}` both in header and in document text, also with `renewcommand`
- renewing `\addlinespace` as above

**Comment by Wandmalfarbe** [comment]
Sadly I can't help with this issue. You could ask on [LaTeX Stack Exchange](https://tex.stackexchange.com/) or [pandoc discuss](https://groups.google.com/g/pandoc-discuss).
