### ISSUE TITLE
Syntax Highlighting Without Listings Cannot Wrap

### ISSUE THREAD

**Issue by Voleking** [Wandmalfarbe/pandoc-latex-template#2]
If I use syntax highlighting without listings. The code cannot wrap just like listings.

![test](https://cloud.githubusercontent.com/assets/13161779/26143457/9e552b3c-3b17-11e7-83a2-bb158b88488e.png)

**Comment by Wandmalfarbe** [comment]
Unfortunately this is a general problem with the verbatim environment and it exists in the default pandoc template as well (see <https://github.com/jgm/pandoc/issues/277>). It seems that there is currently [no way for me to fix this](https://tex.stackexchange.com/questions/14342/verbatim-environment-that-can-break-too-long-lines/14343). 

1. You could insert a manual line break.
2. You could use the listings package for code highlighting with the option `--listings`. Unfortunately the syntax highlighting will be inferior to the one pandoc generates with the verbatim environment.
3. You could replace the `\begin{verbatim}` and `\end{verbatim}` commands with `\begin{spverbatim}` and `\end{spverbatim}`. The package [spverbatim](https://www.ctan.org/pkg/spverbatim?lang=en) seems to handle breaks in verbatim output. You could open a new issue in the pandoc issue tracker suggesting the use of spverbatim.

**Comment by Voleking** [comment]
yeah, package spverbatim worked fine for handling breaks in verbatim output.
But wonder how to replace verbatim with spverbatim by using some command in latex template?

**Comment by Wandmalfarbe** [comment]
I'm no expert at redefining or modifying LaTeX commands but googled a bit around and found this post <https://tex.stackexchange.com/a/309073>. 

I also think it would be possible to use a custom pandoc filter for replacing `\begin{verbatim}` with `\begin{spverbatim}`. You could ask at the [pandoc issue tracker](https://github.com/jgm/pandoc/issues) for such a filter or suggest the use of `spverbatim` as the default verbatim environment.

**Comment by noraj** [comment]
@Wandmalfarbe You could use `fvextra`, see https://stackoverflow.com/questions/20788464/pandoc-doesnt-text-wrap-code-blocks-when-converting-to-pdf#answer-48507868

**Comment by Wandmalfarbe** [comment]
> @Wandmalfarbe You could use `fvextra`, see https://stackoverflow.com/questions/20788464/pandoc-doesnt-text-wrap-code-blocks-when-converting-to-pdf#answer-48507868

Yes, I actually saw that comment (https://github.com/jgm/pandoc/issues/4302#issuecomment-360669013) in the pandoc issue tracker but forgot to implement it. Thank you for reminding me 😄.

> Or see this manual way to do with `xcolor` https://tex.stackexchange.com/questions/323329/pandoc-code-blocks-in-markdown-with-very-long-lines-get-cut-off-when-outputting

This example doesn't actually use `xcolor` to break long lines in code blocks. It uses `listings` with the options

```
breaklines=true,
breakatwhitespace=true,
breakautoindent=true,
```

to break long lines. This only applies when compiling your pandoc document with the option `--listings` and has been [implemented in Eisvogel since day zero](https://github.com/Wandmalfarbe/pandoc-latex-template/commit/1a84bcb0538b77b8c72928dd14080f0db83c4ced#diff-0aa458022c64e642926b2ded90215a09R393).

**Comment by noraj** [comment]
> Yes, I actually saw that comment ([jgm/pandoc#4302 (comment)](https://github.com/jgm/pandoc/issues/4302#issuecomment-360669013)) in the pandoc issue tracker but forgot to implement it. Thank you for reminding me smile.

You're welcome.



> This example doesn't actually use `xcolor` to break long lines in code blocks. It uses `listings` with the options
> 
> ```
> breaklines=true,
> breakatwhitespace=true,
> breakautoindent=true,
> ```
> 
> to break long lines. This only applies when compiling your pandoc document with the option `--listings` and has been [implemented in Eisvogel since day zero](https://github.com/Wandmalfarbe/pandoc-latex-template/commit/1a84bcb0538b77b8c72928dd14080f0db83c4ced#diff-0aa458022c64e642926b2ded90215a09R393).

My bad I didn't read the code :(

**Comment by noraj** [comment]
That was quick, I need to test that :)

**Comment by noraj** [comment]
@Wandmalfarbe I was able to use a better syntax highlight (https://github.com/noraj/OSCP-Exam-Report-Template-Markdown/commit/486237ef5fbffd288fdc8e133667e0f5e9f33ea2) thanks to you :)
I use your LaTeX template for rendering my OSCP markdown template see https://github.com/noraj/OSCP-Exam-Report-Template-Markdown, where I credited your work (if your need to build a gallery section or just because that make you happy to hear that people use your great template).

**Comment by noraj** [comment]
@Wandmalfarbe Still a small issue: When the wrapped line is the last line of a page:

![image](https://user-images.githubusercontent.com/16578570/60461129-e890f000-9c45-11e9-8ccf-0717c1140a87.png)

I goes out of the box.

**Comment by Wandmalfarbe** [comment]
> @Wandmalfarbe I was able to use a better syntax highlight ([noraj/OSCP-Exam-Report-Template-Markdown@486237e](https://github.com/noraj/OSCP-Exam-Report-Template-Markdown/commit/486237ef5fbffd288fdc8e133667e0f5e9f33ea2)) thanks to you :)

It always makes me happy to hear about people using my work and appreciating what I make! That readme looks great!

> Still a small issue: When the wrapped line is the last line of a page:

Please open a new issue so we don't spam this one.
