### ISSUE TITLE
Long lines without spacing aren't broken at all 

### ISSUE THREAD

**Issue by tholok97** [Wandmalfarbe/pandoc-latex-template#20]
*(this issue might already have been adressed in #2)*

Hey! I'm pretty new to both Pandoc and this project, so take my criticism with a hint of salt, but I'd love it if this template took care of breaking long words. 

For example in an assignment I'm writing I needed  to add a long link. I ended up having to shorten it with one of those online shorteners, but I'd love it if the template just took care of that.

Another usage example is long lines of code without spacing (XPath for. Ex.) 

I'm not sure if this is within the scope of this project, but personally I'd love to see linebreaks handled more gracefully :)

**Comment by Wandmalfarbe** [comment]
**URLs**

When you use URLs you should mark them as URLs in your markdown document like so:

```markdown
[I'm an inline-style link](https://www.example.com/some-really-long-url)
```

or

```markdown
<https://www.example.com/some-really-long-url>
````

the `url` package then inserts linebreaks at these special characters `:/.?#&_,;!`.

**Code (Listings)**

The listing environment has the option `breaklines` set to `true` so the XPath Code you have should break correctly when you use listings (with the option `--listings`). It only breaks at special characters like the URL packet.

Could you send me a screenshot of your document?

I did some tests of long lines and URLs without spaces (but with special characters). When using listings and/or URLs everything seems to break nicely:

![screenshot 2017-11-13 19 20 33](https://user-images.githubusercontent.com/17237627/32742041-879bd840-c8a8-11e7-81a3-cc60ca9b2fea.png)

**Comment by tholok97** [comment]
# Thanks for the quick and detailed reply!

A screenshot of my document would have shown exactly what you showed in your excellent demo. I had links in my document that contained long sections of only characters (like your example.com link).

I tested an XPath query also, and my assumption was wrong. It works fine as long as there are no long sections of only characters.

At least **now I know *why* my links weren't being broken up, and I can work around it.** Would be great if the template could figure out a good way to break whatever I threw at it (like your example.com link), but in #2 I think you explained why that's not realistic.

## Thanks!
