### ISSUE TITLE
Pandoc not seeing templates folder

### ISSUE THREAD

**Issue by eo12516** [Wandmalfarbe/pandoc-latex-template#200]
I've followed all of the instructions, created templates folders in both of the locations pandoc says my default user data is, and I keep getting this error:

`Could not find data file templates/eisvogel.latex`

**Comment by nathan72419** [comment]
try specifying the template to be eisvogel.tex rather than just eisvogel

**Comment by nicolai92** [comment]
Have you renamed the file `eisvogel.tex` to `eisvogel.latex` in the template folder? Seems like that's causing the problem ...

**Comment by eo12516** [comment]
> Have you renamed the file `eisvogel.tex` to `eisvogel.latex` in the template folder? Seems like that's causing the problem ...

That worked! Thanks!

**Comment by ryankert01** [comment]
how  to resolve this problem on docker?
```
alias pandock='docker run --rm -v "$(pwd):/data" -u $(id -u):$(id -g) pandoc/extra'
pandock readme.md -o example.pdf --template eisvogel --listings
Unable to find image 'pandoc/extra:latest' locally
latest: Pulling from pandoc/extra
ef5531b6e74e: Already exists 
4e821479e4b5: Already exists 
00f1e069c9e8: Pulling fs layer 
c6b7e74dbfd1: Download complete 
73732c6ec5a1: Download complete 
13d63ff5f1df: Download complete 
984e9b553bec: Download complete 
36f506d57a55: Download complete 
b4a7ca1217f5: Download complete 
057ddd0af801: Download complete 
0e8fc7fd216f: Download complete 
7a9e5ae8d256: Download complete 
3e228e84fa73: Download complete 
bc128267fb7a: Download complete 
8ba2c6e34513: Download complete 
331ae81764c8: Download complete 
291f71adec64: Download complete 
526ac1392c7e: Download complete 
bbf7689041b4: Download complete 
d5f22a0a9693: Download complete 
fbb2e6fff275: Download complete 
^C%                          
```

raise error:
```
pandoc ./readme.md -o ./readme.pdf --from markdown --template eisvogel --listings
Could not find data file templates/eisvogel.latex
```

**Comment by ryankert01** [comment]
> how to resolve this problem on docker?
> 
> ```
> alias pandock='docker run --rm -v "$(pwd):/data" -u $(id -u):$(id -g) pandoc/extra'
> pandock readme.md -o example.pdf --template eisvogel --listings
> Unable to find image 'pandoc/extra:latest' locally
> latest: Pulling from pandoc/extra
> ef5531b6e74e: Already exists 
> 4e821479e4b5: Already exists 
> 00f1e069c9e8: Pulling fs layer 
> c6b7e74dbfd1: Download complete 
> 73732c6ec5a1: Download complete 
> 13d63ff5f1df: Download complete 
> 984e9b553bec: Download complete 
> 36f506d57a55: Download complete 
> b4a7ca1217f5: Download complete 
> 057ddd0af801: Download complete 
> 0e8fc7fd216f: Download complete 
> 7a9e5ae8d256: Download complete 
> 3e228e84fa73: Download complete 
> bc128267fb7a: Download complete 
> 8ba2c6e34513: Download complete 
> 331ae81764c8: Download complete 
> 291f71adec64: Download complete 
> 526ac1392c7e: Download complete 
> bbf7689041b4: Download complete 
> d5f22a0a9693: Download complete 
> fbb2e6fff275: Download complete 
> ^C%                          
> ```
> 
> raise error:
> 
> ```
> pandoc ./readme.md -o ./readme.pdf --from markdown --template eisvogel --listings
> Could not find data file templates/eisvogel.latex
> ```

I solved it using this command

```zsh
ocker run --rm --volume "`pwd`:/data" --user `id -u`:`id -g` pandoc/extra readme.md -o output.pdf --template eisvogel
```
