### ISSUE TITLE
!pdfTeX error: pdflatex (file a_mhce32.enc): cannot open encoding file for reading

### ISSUE THREAD

**Issue by Vo-Alex** [Wandmalfarbe/pandoc-latex-template#203]
Hello,

I using Eisvogel for a while, and had never encountered any problems but when I wanted to use it on a new installation of my pc under **Fedora 33** I encountered the following error message :
```
Error producing PDF.
!pdfTeX error: pdflatex (file a_mhce32.enc): cannot open encoding file for reading
 ==> Fatal error occurred, no output PDF file produced!
```
I can't find where the problem comes from, especially since **texlive-full** is installed and everything worked with **fedora 32**

i hope someone to help me or give me a lead.

**Comment by keeferrourke** [comment]
I just recently encountered this same issue on Fedora 33, after upgrading from Fedora 32 on Friday.
I haven't found a solution that makes the `pdflatex` backend work as it did before, but `xelatex` works just fine :)

Maybe try `--pdf-engine=xelatex` as a workaround for now?

**Comment by Vo-Alex** [comment]
Thank you for your help.

It works fine with `xelatex`.

Can you give me the link to issue on fedora 33 so i can follow this ?

**Comment by keeferrourke** [comment]
Uh sorry, poor choice of words! I'm not aware of any bug that's been filed with Fedora about this issue. I just meant that I had the same problem as you :sweat_smile:

**Comment by Wandmalfarbe** [comment]
This seems like an upstream problem with Fedora 33 and the (bundled?) LaTeX distribution. It might be worth it to remove LaTeX completely and install it again manually. The current `.travis.yml` is a good starting point for a manual installation that should work on Fedora too (https://github.com/Wandmalfarbe/pandoc-latex-template/blob/master/.travis.yml).

```
  # default textlife from apt-get is too old
  # install the latest texlife version manually
  - REMOTE="http://mirror.ctan.org/systems/texlive/tlnet"
  - INSTALL="/tmp/install-texlive"
  - mkdir -p $INSTALL
  - curl -sSL $REMOTE/install-tl-unx.tar.gz | tar -xzv -C $INSTALL --strip-components=1
  - sudo $INSTALL/install-tl -no-gui -profile .texlife.profile
  - VERSION=$($INSTALL/install-tl --version | grep 'version' | grep -o '[0-9]\{4\}')
  - PLATFORM=$($INSTALL/install-tl --print-platform)
  - TEXLIVE_DIR="/usr/local/texlive/${VERSION}"
  - TEXBIN="/usr/local/texlive/${VERSION}/bin/${PLATFORM}"
  - export "PATH=$TEXBIN:$PATH"

  # initialization for tlmgr
  - sudo apt-get install xzdec
  - tlmgr init-usertree
```
