### ISSUE TITLE
template breaks generation of table containing math

### ISSUE THREAD

**Issue by lebedov** [Wandmalfarbe/pandoc-latex-template#208]
When I try to compile a Markdown file `test.md` containing 

```markdown
||||
|---|---|---|
|a. foo|$\geq\mathsf{9\:z/X}$|QQ:$\geq\mathsf{90\:a/B}$|
|b. bar baz mux|$\geq\mathsf{3.0\times 10^3/\mu X}$|SI:$\geq \mathsf{3.0\:AB/C}$|
```
to a pdf using `pandoc --pdf-engine=xelatex test.md --template eisvogel.tex  -o test.pdf`, the following LaTeX error occurs:

```
! Missing number, treated as zero.
<to be read again>
                   (
l.299 ...columnwidth - 2\tabcolsep) * \real{0.33}}
```

Building the pdf without eisvogel succeeds without error.

Any thoughts as to what is going on? I'm using pandoc 2.11.1.1 on MacOS 10.15.7 with MacTeX 2020.0407 and revision [f15e2275](https://github.com/Wandmalfarbe/pandoc-latex-template/commit/f15e2275a7b50ab21d67b09af20a19b676566e4e) of eisvogel.

**Comment by cannyboy** [comment]
Getting this as well. Works ok for non-math stuff (Mathjax).
macOS 11.01, with homebrew-installed mactex-no-gui and pandoc, latest versions.

**Comment by eduardofandrade** [comment]
Also getting this:
```
! Missing number, treated as zero.
<to be read again> 
                   (
l.1798 ...olumnwidth - 1\tabcolsep) * \real{0.09}}
                                                  \raggedright
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on /private/var/folders/w1/bx1d2g1x2slfbhhs2_4x7qh80000gp/T/
tex2pdf.-48beef50b8b8b61d/input.log.

Error producing PDF.
! Missing number, treated as zero.
<to be read again> 
                   (
l.1798 ...olumnwidth - 1\tabcolsep) * \real{0.09}}

make: *** [all] Error 43

```
macOS 10.15.7 with homebrew installed basictex 2020.0407 and pandoc 2.11.2.

**Comment by lebedov** [comment]
If I modify the sample file as follows, it compiles to a PDF successfully:

```
---
header-includes:
    - \usepackage{calc}
    - \usepackage{natbib}
    - \bibliographystyle{named}
---

||||
|---|---|---|
|a. foo|$\geq\mathsf{9\:z/X}$|QQ:$\geq\mathsf{90\:a/B}$|
|b. bar baz mux|$\geq\mathsf{3.0\times 10^3/\mu X}$|SI:$\geq \mathsf{3.0\:AB/C}$|
```

**Comment by Wandmalfarbe** [comment]
The `calc` package was missing when using tables. It was introduced in https://github.com/jgm/pandoc/commit/bd7c9eb32be7c5499f4a50cb4b5f138f9eb919e8. I merged Eisvogel with the default template and the bug should now be fixed.
