### ISSUE TITLE
Biblatex doesn't work

### ISSUE THREAD

**Issue by notaduck** [Wandmalfarbe/pandoc-latex-template#211]
Hi. I am trying to get refernces to work with your template, but I am having a hard time with doing so and I probably think it is a issue with the template.

```
[Pandoc_Template] pandoc -s main.pandoc -o main.pdf --template eisvogel.tex --citeproc 
[WARNING] Could not deduce format from file extension .pandoc
  Defaulting to markdown
Error producing PDF.
! LaTeX Error: Environment CSLReferences undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.298 egin{CSLReferences}
```

```md
---
title: main
author: [Daniel Guldberg Aaes]
date: 13 December 2020
biblatex: true
bibliography: ref.bib
reference-section-title: "References"
---


# Visu habeoque

## Fragmina clausa surgimus bibes

Lorem markdownum corpus adsuetaque nurus iamque implevit. Adolentur enim: sed
esse bubo *Burin desiluit* missum ait differt nunc nostri aura ullos. Iunctus
vitta humum, ex magna fortibus [@IO]

```

```bib
@misc{ IO,
  title = {Operating Systems and C11. I/O},
  author = {Philippe Bonnet},
  note  =  {\url{https://learnit.itu.dk/pluginfile.php/250755/course/section/124444/IO.pdf}},
  note = {Accessed: 07-12-2020},
}
```

**Comment by tbrandvik** [comment]
This is just a quick note to say that I have the same issue.

**Comment by daniel-vera-g** [comment]
Hey, I could not reproduce your issue :confused: 

I assume that it's an error with your latex setup/installation and you're missing some latex package:
> ! LaTeX Error: Environment CSLReferences undefined.

Instead of `...--template eisvogel.tex...` I used `...--template eisvogel ...`. But I don't think, that this is your problem.

**Comment by cagix** [comment]
i've seen this before in my own pandoc toolchain. iirc there were some recent changes in pandoc and/or the default latex template. 

@notaduck could you check please with the standard latex template and a recent pandoc version?

**Comment by notaduck** [comment]
@cagix I am sorry to say that I won't be able to reproduce this again. My old drive died and I lost the paper.

**Comment by technikfischer** [comment]
I don't know if this helps in any way, but I had the same problem. After starting to try random things to fix it i found it working by replacing `template: eisvogel` with its full url like `template: https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.tex` (I'm using a defaults file, but i don't think that matters). 

I have no idea why that would change anything, but I wanted to share this information because it took me some time and maybe it helps someone else.

**Comment by drupol** [comment]
Sharing the same issue.
