### ISSUE TITLE
Excluding a header in book option

### ISSUE THREAD

**Issue by longErste** [Wandmalfarbe/pandoc-latex-template#213]
Is there a way to exclude some headers, such as appendix from creating the book like title page ?

**Comment by Wandmalfarbe** [comment]
As one can see in https://github.com/jgm/pandoc/issues/1762, pandoc added support for hiding sections in the table of contents like this:

``` md
Some Heading {.unnumbered .unlisted}
```

To quote [the pandoc manual](https://pandoc.org/MANUAL.html#heading-identifiers):

> If the unlisted class is present in addition to unnumbered, the heading will not be included in a table of contents. (Currently this feature is only implemented for certain formats: those based on LaTeX and HTML, PowerPoint, and RTF.)
