### ISSUE TITLE
Add options to enable vertical borders in table

### ISSUE THREAD

**Issue by pandysong** [Wandmalfarbe/pandoc-latex-template#215]
Is it possible to add vertical borders in the table (need it when rendering to pdf).

**Comment by Wandmalfarbe** [comment]
Pandoc has currently no built-in support for vertical borders in tables (see https://github.com/jgm/pandoc/issues/922).

> Is it possible to add vertical borders in the table (need it when rendering to pdf).

I think this might be possible with some serious redefinition of environments/commands, so I'm not going to implement it in Eisvogel. There are some workarounds in the mentioned pandoc issue that you can try though.
