### ISSUE TITLE
logo-width should not automatically use 'pt' to allow other units or \textwidth

### ISSUE THREAD

**Issue by Fabioni** [Wandmalfarbe/pandoc-latex-template#221]
https://github.com/Wandmalfarbe/pandoc-latex-template/blob/27fb7e455536012aa7e92151ffad28ff70986f41/eisvogel.tex#L945

Hello,
I wanted to put the logo of my University on the title page and would like to specify the width with `\\textwidth` or 75%.
With the current implementation this does not seem to be possible since in the template `pt` is hardcoded. I would like to remove that hardcoded `pt` so everyone can use what he/she wants. No big deal in my opinion or is there a specific reason for that? Furthermore I would put the date at different position, or at least give the option for that. Check out the picture if you like it.

![image](https://user-images.githubusercontent.com/45362676/105737978-d583f600-5f36-11eb-813a-66b9a0970e37.png)

**Comment by Wandmalfarbe** [comment]
I removed the hard coded unit `pt`. Please take a look in the manual for the available units or feel free to use something like `\textwidth` (which needs to be escaped when specifying in YAML front matter e.g. `\\textwidth`).
