### ISSUE TITLE
Setting link, cite, URL color with HTML-style values?

### ISSUE THREAD

**Issue by slhck** [Wandmalfarbe/pandoc-latex-template#23]
Thanks for the great template!

I see that there are additional options that could be set, e.g.: linkcolor, citecolor, urlcolor. However, setting them as additional variables like the title page color etc. does not work, as they only seem to take `xcolor` names, not HTML-style `FFFFFF` values:

```
Error producing PDF.
! Package xcolor Error: Undefined color `006666'.

See the xcolor package documentation for explanation.
```

**Comment by slhck** [comment]
Never mind, I see that this is a pandoc default, so it's something that should be possible upstream.

**Comment by St-Ex** [comment]
In case someone else find himself here, I've done it on .yml file like this
```yml
    linkcolor: "{HTML}{006666}"
```
