### ISSUE TITLE
How to generate a Beamer type PDF file?

### ISSUE THREAD

**Issue by Skalate** [Wandmalfarbe/pandoc-latex-template#237]
I readed at the file named _eisvogel.latex_, try to find a way to generate beamer. But I can't do it. 
In addition, I use the code `-V ignorenonframetext`. Causes the code box to disappear, and I can't recover it. 
I hope the author or someone else can help answer questions. Thank you very much.

**Comment by Wandmalfarbe** [comment]
In the example `beamer` should be everything you need: https://github.com/Wandmalfarbe/pandoc-latex-template/tree/master/examples/beamer. The file `build.sh` contains the full command to build the PDF. Please have a look at my comment in #218 and keep in mind that beamer is not officially supported.
