### ISSUE TITLE
Add More Text to the Titlepage

### ISSUE THREAD

**Issue by marius-mm** [Wandmalfarbe/pandoc-latex-template#255]
What would be the procedure to put more stuff on the titlepage?

**Comment by cagix** [comment]
@marius-mm You would have to modify the title page of Eisvogel (https://github.com/cagix/pandoc-thesis/blob/master/titlepage.tex, lines 885 to 960). If you use variables (see Pandoc templates: https://pandoc.org/MANUAL.html#templates, you can set them via the metadata, for example.  Alternatively, you can define your own title page, have a look at https://github.com/cagix/pandoc-thesis/blob/master/titlepage.tex.
