### ISSUE TITLE
Question regarding the licence

### ISSUE THREAD

**Issue by Lukas2112** [Wandmalfarbe/pandoc-latex-template#257]
As far as I could see at https://github.com/Wandmalfarbe/pandoc-latex-template/blob/master/LICENSE the license would allow the handout to be adapted so that schools could use it for internship reports, right?

**Comment by Wandmalfarbe** [comment]
The license is an unmodified BSD-3-Clause (https://en.m.wikipedia.org/wiki/BSD_licenses). It should be fine for this use case. However, Im not a lawyer so you might want to ask a professional about that.
