### ISSUE TITLE
Titlepage does not fill the whole PDF page

### ISSUE THREAD

**Issue by Kaszanas** [Wandmalfarbe/pandoc-latex-template#258]
Currently as I am attempting to use this template it produces unreliable output.

For example when using the following YAML information:
```
---
title: "Test Title"
author: [Kaszanas]
date: "2021-09-24"
subtitle: "This is a test title"
lang: "pl"
titlepage: true
book: true
toc-own-page: true
---
```

It produces a faulty titlepage:

![image](https://user-images.githubusercontent.com/34846245/134821573-052b485b-4338-4882-90d9-f8e6ea4bb6db.png)

And even though within the README file it is specified that the default chapter number is set to 1 the chapters start from:

![image](https://user-images.githubusercontent.com/34846245/134821623-bfe95f88-bfa5-41ce-ad36-ae2e893136b5.png)

Same happens when attempting to use the provided PDF backgrounds. It doesn't scale the PDF background properly and is overall unreliable.

Please let me know if anyone knows how to fix this.

**Comment by Kaszanas** [comment]
I have just downloaded the example files and compiled a PDF using them and the problem went away. I think it might be because of some parameters and the order that they are defined?

**Comment by Wandmalfarbe** [comment]
The title page in your post looks good to me. I don't see the problem there.

The chapter numbers look strange because you might be using the wrong heading level. Please have a look at #114 and the mentioned examples there (in particular the comment https://github.com/Wandmalfarbe/pandoc-latex-template/issues/114#issuecomment-528210505).

**Comment by Kaszanas** [comment]
I have ultimately solved this problem somehow, and I am unable to reproduce it.
I will have a look at the issues that You have pointed out. Thank You for Your time!
