### ISSUE TITLE
Example `boxes-with-pandoc-latex-environment-and-awesomebox` displays `-NoValue-`

### ISSUE THREAD

**Issue by Wandmalfarbe** [Wandmalfarbe/pandoc-latex-template#268]
The Example `boxes-with-pandoc-latex-environment-and-awesomebox` changed significantly in commit 3b91566da21ccdb3e4cbf0897228dc8b73405a67. There is `-NoValue-` inserted after the `awesomebox` icon, which is undesired.

This may be a result of the addition of GitHub actions (#267) and the PDF generation with that workflow.

![preview](https://user-images.githubusercontent.com/17237627/141677073-b67cf576-c3bb-40b0-95a9-0138a9208d45.png)

**Comment by sosiristseng** [comment]
OK, I'll check that out later.

**Comment by Wandmalfarbe** [comment]
This seems to be a LaTeX problem. The package `awesomebox` depends on `xparse` which has this in the manual:

> Given as r⟨token1⟩⟨token2⟩, this denotes a “required” delimited argument, where
the delimiters are ⟨token1⟩ and ⟨token2⟩. If the opening delimiter ⟨token1⟩ is
missing, the default marker -NoValue- will be inserted after a suitable error.

**Comment by sosiristseng** [comment]
Trying the instructions from ctan.

https://www.ctan.org/pkg/awesomebox

> The package depends on `fontawesome5`, `xcolor`, `array`, and `xparse`.

**Comment by Wandmalfarbe** [comment]
I installed the latest TeX Live locally and updated all packages, and now I can reproduce the problem. This seems to be introduces by an update to `awesomebox` or its dependencies.

**Comment by supcik** [comment]
I also faced this problem. Instead of building my own texlive from the sources, I am using a ready-made docker image from November 7, and it still produces the correct result :

registry.gitlab.com/islandoftex/images/texlive:TL2021-2021-11-07-04-05

The latest version (November 14) introduced the problem.

**Comment by Wandmalfarbe** [comment]
This was likely a problem of some updated latex packages. Anyway, the problem went away with enough time (and a rebuild with newer packages) :)
