### ISSUE TITLE
Error producing PDF. ! LaTeX Error: Missing \begin{document} in Windows

### ISSUE THREAD

**Issue by Protarios** [Wandmalfarbe/pandoc-latex-template#27]
Template works perfect in Linux environment. In Windows (7) unfortunately I get only the error message

```
Error producing PDF.
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.384   \kvsetkeys{mdf}{framemethod=default,}

```
Pandoc works fine with other templates. I tried the examples from github folder here with same result.

**Comment by Protarios** [comment]
By generating tex code through pandoc, I found that the problem results from the blockquote definition.
If I remove this part from the tex file it compiles:

````
%
% blockquote
%
\definecolor{blockquote-border}{RGB}{221,221,221}
\definecolor{blockquote-text}{RGB}{119,119,119}
\usepackage{mdframed}
\newmdenv[rightline=false,bottomline=false,topline=false,linewidth=3pt,linecolor=blockquote-border,skipabove=\parskip]{customblockquote}
\renewenvironment{quote}{\begin{customblockquote}\list{}{\rightmargin=0em\leftmargin=0em}%
\item\relax\color{blockquote-text}\ignorespaces}{\unskip\unskip\endlist\end{customblockquote}}
```

**Comment by Wandmalfarbe** [comment]
This seems to be a very recent problem with the package `etoolbox`: <https://tex.stackexchange.com/questions/414079/mdframed-broken-in-texlive2017>. You can update your packages via the MiKTeX package manager and the problem should go away.

**Comment by Protarios** [comment]
Unfortunately that dies not help. But putting the most recent toolbox files directly in the project folder works. Also manually updating the etoolbox package in the minted folder does not help.
Problem only occurs in Windows though. No problems with texlive installation in Ubuntu.
