### ISSUE TITLE
Latex error \footref already defined

### ISSUE THREAD

**Issue by sahumphreys** [Wandmalfarbe/pandoc-latex-template#271]
Just found this error popping up on a system that was previously working fine:

stderr: Error producing PDF.
! LaTeX Error: Command \footref already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.6172 }

The file being converted is just a basic test markdown file, and calling on pandoc (v 2.9) to convert using the eisvogel template:

pandoc test.md --pdf-engine=xelatex --from markdown --template=eisvogel -o test.pdf

(Windows 10 OS, Pandoc 2.9, Miktex)

Any thoughts?

**Comment by Th30n3and0nly** [comment]
I ran into the same issue (Linux, pdfTeX 3.141592653-2.6-1.40.23 (TeX Live 2021/Arch Linux), pandoc 2.17.1.1).

Without having a deep understanding on how to properly fix this, I was able to get it to work with the help of https://komascript.de/release3.32 (known issues).

Try to add `\let\footref\relax` before `\documentclass[ ...` in the template file `eisvogel.latex`
