### ISSUE TITLE
How to change the position of the title

### ISSUE THREAD

**Issue by moranliuyu** [Wandmalfarbe/pandoc-latex-template#281]
thank you very much for this template.

I want to change the position of title，for example raise the position of the title，but i donnot know how to solve it.

**Comment by AlbertDM** [comment]
Hi, I am facing the same issue. And also how to increase the size of the title.

Thanks!!!

**Comment by YaZasnyal** [comment]
I think that the only way is to fork template and change it yourself because as I can see there is no additional options for that.

**Comment by Wandmalfarbe** [comment]
> I want to change the position of title，for example raise the position of the title，but i donnot know how to solve it.

I'm afraid this is currently not possible without modifying the template or generated LaTeX code. You can play around with the following lines to change the title page:

https://github.com/Wandmalfarbe/pandoc-latex-template/blob/f5c1f20c94fa7fef4750ce46589416520bd76768/eisvogel.tex#L868-L944

The title page has different layouts when using a background image or not. The following lines are responsible for the text on the title page.

https://github.com/Wandmalfarbe/pandoc-latex-template/blob/f5c1f20c94fa7fef4750ce46589416520bd76768/eisvogel.tex#L897-L922
