### ISSUE TITLE
titlepage-logo parameter is unused

### ISSUE THREAD

**Issue by remi-pr** [Wandmalfarbe/pandoc-latex-template#284]
Hi and thanks for this template.

I think the titlepage-logo parameter is unused, though it controls the packages imported, it does not do the graphics inclusion, this is still using the logo parameter instead as one can see [here](https://github.com/Wandmalfarbe/pandoc-latex-template/blob/30cfc57a0c64fad1202aa1422e2ed3a77535bf02/eisvogel.tex#L528).

Cheers

**Comment by Wandmalfarbe** [comment]
The linked part is for the generation of beamer documents, which use `$logo$` to display a background image on the slides. This becomes clear with a bit of indentation:

```
$if(beamer)$
    $if(institute)$
        \institute{$for(institute)$$institute$$sep$ \and $endfor$}
    $endif$
    $if(titlegraphic)$
        \titlegraphic{\includegraphics{$titlegraphic$}}
    $endif$
    $if(logo)$
        \logo{\includegraphics{$logo$}}
    $endif$
$endif$
```

I mixed/overwrote the variables by accident, but that has been fixed (see https://github.com/Wandmalfarbe/pandoc-latex-template/issues/265).
