### ISSUE TITLE
Color for table rows is applied to some table-like environments.

### ISSUE THREAD

**Issue by Wandmalfarbe** [Wandmalfarbe/pandoc-latex-template#30]
Table row coloring is used in some environments like `array` or `cases` where no coloring is expected.

```latex
\begin{equation}
\ref{eq:pos-clamping-complete}
x_d \notin [x_{min}, x_{max}] \Rightarrow 
\begin{cases}
& v_d \leftarrow 0\\
x_d < x_{min} \Rightarrow & x_d \leftarrow x_{min}\\
x_d > x_{max} \Rightarrow & x_d \leftarrow x_{max}\\
\end{cases}
\end{equation}
```

<img width="387" alt="screen shot 2018-02-28 at 22 14 50" src="https://user-images.githubusercontent.com/17237627/36813944-6d12f51c-1cd6-11e8-98bd-00dbee9bee92.png">

**Comment by Amarandus** [comment]
I noticed this problem, too.
When only using `pmatrix` environments, everything works fine, but as soon as I introduce a table (I'm converting from markdown to latex/pdf), it also colors the previously fine matrices.
