### ISSUE TITLE
Document font color and background color

### ISSUE THREAD

**Issue by venzen** [Wandmalfarbe/pandoc-latex-template#302]
Is there a specific stanza in the template code where I can specify document font and background color?

I'm simply trying to create a dark theme (black page with white text) so I don't have to fry my retinae when rendering PDFs at night. :)

**Comment by Wandmalfarbe** [comment]
This is currently not possible. Usually it is the responsibility of the PDF viewer application to apply a dark mode even to the PDF. [Adobe Acrobat has such a dark mode](https://www.makeuseof.com/tag/give-adobe-reader-a-dark-theme-for-easier-pdf-reading/) and [Foxit Reader has one too](https://techdows.com/2021/10/foxit-reader-11-dark-skin.html).
