### ISSUE TITLE
[doc] New official docker image `pandoc/extra`  includes eisvogel

### ISSUE THREAD

**Issue by daamien** [Wandmalfarbe/pandoc-latex-template#318]
Hi @Wandmalfarbe !

Just to let you know that a new pandoc docker image is available here:

https://hub.docker.com/r/pandoc/extra

The goal of this image is to include useful templates and filters. The eisvogel template is the first template included. 

In other words, people can now use the template without installing anything :

```sh
docker run --rm -v "$(pwd):/data" -u $(id -u) pandoc/extra --template=eisvogel foo.md -o foo.pdf
```

I think it may be useful to add this line in README, I can submit a PR if you think it's helpful

**Comment by Wandmalfarbe** [comment]
That is really cool! I'd love to see your PR.

**Comment by Wandmalfarbe** [comment]
Thank you for your contribution!
