### ISSUE TITLE
Use the template in a thesis-like project

### ISSUE THREAD

**Issue by FrancescoFilippi** [Wandmalfarbe/pandoc-latex-template#32]
Let me point out that I'm quite new to the TeX world.
Is it possible to use such a template in a thesis-like project? More specifically I'd like to add a few things to the template:

- Some kink of logo to the first page
- A table of content that keeps track of the markdown headers (in a multi-markdown numbered pages scenario )
- being able to add one (or more) footnotes to the pages

Thanks.

**Comment by Wandmalfarbe** [comment]
> - Some kind of logo to the first page

You can do that with the `includegraphics` command. [Here is an example](https://github.com/breiting/breiting/blob/46e8180b3b357263eef515f8774e0e17a4602f05/roles/dotfiles/files/.pandoc/templates/robotic.latex#L704) of how you could do it. The [result looks like this](https://github.com/breiting/breiting/blob/46e8180b3b357263eef515f8774e0e17a4602f05/roles/dotfiles/files/.pandoc/templates/sample.pdf).

> - A table of content that keeps track of the markdown headers (in a multi-markdown numbered pages scenario )

A table of content is included in the document by adding the option `--toc` when running pandoc. You could also add one manually somewhere in the document with `\tableofcontents` by writing raw LaTeX mixed in your markdown. Keep in mind that the latex-commands don't get converted when using some other output format like HTML or DOCX.

> - being able to add one (or more) footnotes to the pages

The syntax for footnotes in Pandoc markdown is like this:

```markdown
Some sentence in your document.^[This is a footnote.] This is another sentence.
```

**Comment by FrancescoFilippi** [comment]
Thank you so much. That's perfect!
