### ISSUE TITLE
with --listings,  character `è` becomes `é`

### ISSUE THREAD

**Issue by daamien** [Wandmalfarbe/pandoc-latex-template#324]
More French problems :)

In the  `eisvogel_listing_style` section here
https://github.com/Wandmalfarbe/pandoc-latex-template/blob/master/eisvogel.tex#L772

* `é` becomes `\'e`
* `è` also becomes `\'e` but it should be  ``\`e``

As decribed here:

https://en.wikibooks.org/wiki/LaTeX/Source_Code_Listings#Encoding_issue

@Wandmalfarbe: Also would you be open to add support for more UTF8 characters in this list or do you want to keep as short as possible ?

**Comment by Wandmalfarbe** [comment]
Ah, nice find! I used the Wiki you linked as an inspiration. I think Eisvogel and the Wiki have the wrong definition for `È`... Could you also change that here, please?

* `È` also becomes `\'E` but it should be  ``\`E``

> Also would you be open to add support for more UTF8 characters in this list or do you want to keep as short as possible ?

Feel free to add as many as you like (in a separate PR). I don't think the compilation time will increase that much, but I'm no expert at that. I think the benefits of more supported characters in Listings outweigh the Possibility of an increased compilation time.
