### ISSUE TITLE
How to unify the Asian font and Latin font?

### ISSUE THREAD

**Issue by krahets** [Wandmalfarbe/pandoc-latex-template#326]
I followed the build script provided in `langage-chinese/build.sh` with `CJKmainfont="Noto Sans SC`.

```
# No lang option (-V lang=zh) here because Chinese is unsupported in polyglossia and babel.
pandoc "document.md" -o "document.pdf" --from markdown --template "../../eisvogel.tex" --listings --pdf-engine "xelatex" -V CJKmainfont="Noto Sans SC"
```

The output is great overall! But the English char is a little bigger than the Chinese char. I'm wondering about how to unify the Latin font and Asian font. Thanks!

<img width="635" alt="image" src="https://user-images.githubusercontent.com/26993056/219378252-d97daeb3-f503-4244-89f5-a937c8663f3c.png">

**Comment by raiots** [comment]
Same issue, how do you solve it? Thanks.

**Comment by krahets** [comment]
@raiots Try to use another font such as Noto Sans Serif

**Comment by krahets** [comment]
> fixed it, thanks a lot! I was thought there is someway to specific set fonts for English lol.

Same as your thoughts.
