### ISSUE TITLE
Feature Request: Add option to use additional packages

### ISSUE THREAD

**Issue by firefart** [Wandmalfarbe/pandoc-latex-template#329]
It would be great to add an option to add additional packages through the yml header.

If I want to `\usepackage{pgf-pie}` for example (to generate pie charts) this is currently not possible because the `\usepackage` instructions must come before `\being{document}`.

I would suggest adding an array of packages to the yml section and then looping over all of them and add `\usepackage` instructions for every single one.

**Comment by firefart** [comment]
@daamien Yes but this option also includes the contents after the `\begin{document}`. This just inserts the content at the beginning of the body, but the `\usepackage` needs to be before `\begin`.

**Comment by firefart** [comment]
Ok managed it with the following in the metadata yml:

```yml
header-includes: |
  \usepackage{tikz}
  \usepackage{pgf-pie}
```

Thanks!

**Comment by daamien** [comment]
How about  `--include-in-header=`  and `header-includes:` then ?
