### ISSUE TITLE
Multiple authors below each other

### ISSUE THREAD

**Issue by Stefan-Ilic** [Wandmalfarbe/pandoc-latex-template#33]
Would it be possible to display multiple authors in the title page below each other and not coma-separated?

**Comment by Wandmalfarbe** [comment]
Yes, that should be quite easy. You have to replace [this line](https://github.com/Wandmalfarbe/pandoc-latex-template/blob/master/eisvogel.tex#L693)

```tex
{\Large \textsf{\MakeUppercase{$for(author)$$author$$sep$, $endfor$}}
```

by that line

```tex
{\Large \textsf{$for(author)$$author$$sep$\\ $endfor$}
```

**Comment by Stefan-Ilic** [comment]
Yes, that worked, thank you very much!
