### ISSUE TITLE
Display error after level 4 headings

### ISSUE THREAD

**Issue by RonnyFiebigDVTS** [Wandmalfarbe/pandoc-latex-template#332]
I noticed that after exporting PDF from Markdown to PDF with the Latex template, I always have display errors for all objects after a Level 4 heading. Especially nice to see is that with code blocks, but also simple text is displayed incorrectly after a level 4 heading.

Output in PDF:
![image](https://user-images.githubusercontent.com/54892321/225250583-f023f4e1-d195-4a72-951c-fdcaef462d13.png)

Same Section in Markdown:
![image](https://user-images.githubusercontent.com/54892321/225250986-fc4dd9d7-ab1a-4baf-b1f9-dbad25da19d2.png)

Other example:
![image](https://user-images.githubusercontent.com/54892321/225250680-d63dfac3-8215-43ba-a683-0e4d5c695c39.png)

**Comment by Wandmalfarbe** [comment]
Headings with level 5 or above are displayed as run-in when using latex. Please have a look at [block-headings: true](https://pandoc.org/MANUAL.html#layout) to format, these headings as block level headings.
