### ISSUE TITLE
including external pdf

### ISSUE THREAD

**Issue by stzi** [Wandmalfarbe/pandoc-latex-template#35]
I have a document in markdown and i want to attach some other documents in pdf. I tried to add 
`header-includes: \usepackage{pdfpages}` in the YAML preamble. This unfortunately gives me:

```
Error producing PDF.
! LaTeX Error: Option clash for package xcolor.
```

I have edited the template and added `\usepackage{pdfpages}` after the `\usepackage{xcolor}`stuff around line 430. This fixes the error for me but I am unsure if it is the right thing to do. 

By the way, is there a way to include a PDF page in a Document so that it gets scaled down a bit and is surrounded by the page header and footer, numbering etc.?

**Comment by Wandmalfarbe** [comment]
>I have a document in markdown and i want to attach some other documents in pdf. I tried to add 
`header-includes: \usepackage{pdfpages}` in the YAML preamble. This unfortunately gives me:
>
>```
>Error producing PDF.
>! LaTeX Error: Option clash for package xcolor.
>```

Yes, it is possible that the location where `header-includes` puts the LaTeX code is too early or too late (depending on the included code). 

>I have edited the template and added `\usepackage{pdfpages}` after the `\usepackage{xcolor}`stuff around line 430. This fixes the error for me but I am unsure if it is the right thing to do. 

That is the correct solution. You need to include the package after `xcolor`. You [could also see what option caused the option clash and modify the xcolor options.](https://tex.stackexchange.com/a/83102)

>By the way, is there a way to include a PDF page in a Document so that it gets scaled down a bit and is surrounded by the page header and footer, numbering etc.?

I have no experience with including (multipage) PDFs in LaTeX documents but you can include a PDF like a normal image in markdown:

```
![This is the caption text.](some-pdf-file.pdf)
```

To make it a bit smaller you could [specify a size of the image](https://pandoc.org/MANUAL.html#images) with pandoc markdown:

```
![This is the caption text.](some-pdf-file.pdf){ width=50% }
```

**Comment by stzi** [comment]
Thank you for your fast response! 

Well, just including it in markdown was a bit to obvious for me, and worst of all, it would have worked right away and provided exactly the result I was looking for :-)

Maybe, if nothing else breaks by doing it,  it would be a good idea to modify the template on github so it can handle \usepackage{pdfpages}, after all I can think of it to be useful.
