### ISSUE TITLE
toc-own-page: true - not working

### ISSUE THREAD

**Issue by jithurbide-CPNV** [Wandmalfarbe/pandoc-latex-template#359]
Hello,

I setup the template on m page with "toc-own-page: true". No new page after table of content. Did I setup something wrong. Here are my setup :

---
title:SQL1
author: me
keywords: [DataBase, MLD, SQL1]
subtitle: "Bonne pratique du MLD"
lang: "fr"
toc-own-page: true
titlepage: true
titlepage-logo: "./images/logo.png"
logo: "./images/logo-small.png"
header-right: "XXXX-ES"

**Comment by Ci7rix** [comment]
You have to enable the TOC in the document option as follows :
```
---
title: SQL1
author: me
keywords: [DataBase, MLD, SQL1]
subtitle: "Bonne pratique du MLD"
lang: "fr"
toc: true
toc-own-page: true
titlepage: true
titlepage-logo: "./images/logo.png"
logo: "./images/logo-small.png"
header-right: "XXXX-ES"
...
```

Nice to see that the CPNV using MarkDown ;-)

**Comment by jithurbide-CPNV** [comment]
it's working with : toc: true
