### ISSUE TITLE
Add support for tikz

### ISSUE THREAD

**Issue by JulHee** [Wandmalfarbe/pandoc-latex-template#36]
Would it be possible to add support for tikz, so that projects like [pandoc-filter-graphviz
](https://github.com/Hakuyume/pandoc-filter-graphviz) can be used with this template ? I made an pull request with my changes to the code base  #37  .

It would then be possible to create tikz-pictures using pandoc filters, like:

` pandoc -F ./pandoc-filter-graphviz example.md -o example.pdf --from markdown --template eisvogel --listings -V tikz`

**Comment by Wandmalfarbe** [comment]
What you need is already possible without a custom variable. Pandoc has a variable `header-includes` that can put raw latex in your preamble. For tikz support you can use the following markdown:

```md
---
title: "My document with tikz support"
author: [Author Name]
date: 2017-12-12
header-includes: | 
 \usepackage{tikz}
 \usetikzlibrary{positioning}
 \usetikzlibrary{arrows}
...

# This document contains a tikz drawing

\begin{tikzpicture}[>=triangle 45,font=\sffamily]
    \node (X) at (0,0) {x};
    \node (Y) [below left=2cm and 1cm of X]  {y};% 2cm below, 1cm to the left (optional)
    \node (Z) [below right=2cm and 1cm of X] {z};
    \node (U) [below left=2cm and 1cm of Z]  {u};
    \draw [semithick,->] (X) -- (Y);
    \draw [semithick,->] (X) -- (Z);
    \draw [semithick,->] (Y) -- (U) node [midway,below,sloped] {*};
    \draw [semithick,->] (Z) -- (U) node [midway,below,sloped] {*};
\end{tikzpicture}
```

With this technique it is also possible to include additional tikz libraries without changing the template every time.

**Comment by JulHee** [comment]
I didn't know about this option, but it seems that it adds the tikz before the package `xcolor` resulting in an error:

~~~
Error producing PDF.
! LaTeX Error: Option clash for package xcolor.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.133
~~~

**Comment by Wandmalfarbe** [comment]
Can you show me your value for `header-includes`? The above example compiles without errors for me. Maybe you have an outdated TeX installation?
