### ISSUE TITLE
imgage resize

### ISSUE THREAD

**Issue by jithurbide-CPNV** [Wandmalfarbe/pandoc-latex-template#360]
Hello,

Probably not the right place but, I can't resize my image during export. I use this in mk  :

"<img src="tab1.png" style="width:40%;">"

I see the resizing image on typora but the final pdf as only full size image. Can someone have any idea, why ?

Julien

**Comment by cagix** [comment]
you could give something like `![](tab1.png){width="80%"}` a try (see https://pandoc.org/MANUAL.html#images).

**Comment by jithurbide-CPNV** [comment]
ok with --listings options it's working. thanks a lot!

**Comment by cagix** [comment]
> ok with --listings options it's working. thanks a lot!

strange. this should work no matter what syntax highlighting is used for code blocks?
