### ISSUE TITLE
Unable to display Image

### ISSUE THREAD

**Issue by lrmatheen** [Wandmalfarbe/pandoc-latex-template#394]
I am able to apply eisvogel template to a md file where there are no images. md file with images are not converted to pdf. Attaching my zipped folder here.
Error shown is:
Error producing PDF.
! Undefined control sequence.
l.404 \pandocbounded

[experiment.zip](https://github.com/user-attachments/files/16487856/experiment.zip)

**Comment by jlopezr** [comment]
I have the same problem...

**Comment by chdemko** [comment]
See #192

**Comment by lrmatheen** [comment]
> See #192

Thanks, Solved my issue, #392

**Comment by Wandmalfarbe** [comment]
This should be fixed in [version 2.5.0](https://github.com/Wandmalfarbe/pandoc-latex-template/releases/tag/v2.5.0).
