### ISSUE TITLE
Idiomatic way to turn off page headers and footers?

### ISSUE THREAD

**Issue by ornamentist** [Wandmalfarbe/pandoc-latex-template#40]
Thanks for creating this template -- the resulting PDF documents are excellent.

Is there an idiomatic way to turn off page headers and footers in the resulting LaTeX/PDF?  (This is for a smallish, special-purpose document).

**Comment by Wandmalfarbe** [comment]
I may add a way to disable headers and footers in the future. For now you need to remove all lines including [641](https://github.com/Wandmalfarbe/pandoc-latex-template/blob/40b00f300237780f2f5486ca88a18d987ad6bcd2/eisvogel.tex#L641) to [652](https://github.com/Wandmalfarbe/pandoc-latex-template/blob/40b00f300237780f2f5486ca88a18d987ad6bcd2/eisvogel.tex#L652).

**Comment by ornamentist** [comment]
Thanks, that's a useful workaround.

**Comment by zareami10** [comment]
It would be nice if we could disable headers/footers separately.

**Comment by Iksas** [comment]
All headers and footers can be disabled separately by setting them to `"\\\ "` :

`header-right: "\\\ "`
`footer-left: "\\\ "`
...and so on

**Comment by neilernst** [comment]
please document @Iksas comment in the main docs - took forever to find this (tried `"", false, no, " "` etc)

> All headers and footers can be disabled separately by setting them to `"\\\ "` :
> 
> `header-right: "\\\ "` `footer-left: "\\\ "` ...and so on

**Comment by GregoryKogan** [comment]
As I mentioned [in this issue](https://github.com/Wandmalfarbe/pandoc-latex-template/issues/379#issuecomment-1987230442) it's possible to completely remove footers by setting `footskip` to something relatively larger than bottom margin and for headers setting `headsep` to something larger than top margin. This will push footers/headers out of the page.
