### ISSUE TITLE
Modify inline code

### ISSUE THREAD

**Issue by alrevuelta** [Wandmalfarbe/pandoc-latex-template#404]
I would like to change the color and background of inline code, which is the one between quotes like \`code\`.

The style I would like is similar to github `code` with a grey background.

Have tried many things but none of them are even close to working.

In other words. I want to render \`code\` to `code` (with Github like style)

**Comment by Wandmalfarbe** [comment]
It can be done but the solution mentioned here https://tex.stackexchange.com/a/36431 has drawbacks when the inline listing spans over two lines. Years ago I tried some of the mentioned solutions but it was kind of brittle so I didn't include it into Eisvogel.

**Comment by alrevuelta** [comment]
Thanks for the answer. Not sure I understand the solution. Is that supposed to work with \`code\`? Don't mind about it spanning multiple lines.
