### ISSUE TITLE
number items give latex error

### ISSUE THREAD

**Issue by micshr** [Wandmalfarbe/pandoc-latex-template#41]
For example trying the basic example:

```bash
pandoc --from markdown --template eisvogel -i basic-example.md -o output.pdf
```

Gives following error output:

```bash
Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.357   D
         e neque iura aquis

./output.tex:357: LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.357   D
         e neque iura aquis
```

Seems that the error occurs when using numbered lists. For example:

1. first test list item
2. second test list item

I'm running the command in windows 10, pandoc version 2.2.1 and MikTex 2.9

**Comment by Wandmalfarbe** [comment]
Thank you for reporting an issue. It seems that your command contains the wrong option `-i`. The input file is [denoted with the option `-f` or `-r`](https://pandoc.org/MANUAL.html#general-options). You can also use the long names `--from` or `--to` which make it more clear what they do.
