### ISSUE TITLE
Add background to inline code

### ISSUE THREAD

**Issue by Stefan-Ilic** [Wandmalfarbe/pandoc-latex-template#42]
Hey, still a big fan of this template,

I was just wondering if there is a way to add a background to inline code rather than color, like `this`.

**Comment by Wandmalfarbe** [comment]
Unfortunately, `\lstinline` does not support background colors or borders. The documentation for the listings package states:

> `\lstinline` [...] works like `\verb` but respects the active language and style. These listings use flexible columns unless requested differently in the optional argument, and do not support frames or background colors.

If you really need this feature you could use some [hacky solutions like these](https://tex.stackexchange.com/q/357227). However, I will not integrate them into the template.

**Comment by teoman002** [comment]
Another solution from: https://jdhao.github.io/2019/05/30/markdown2pdf_pandoc/
```
\usepackage{xcolor}

% change background color for inline code in
% markdown files. The following code does not work well for
% long text as the text will exceed the page boundary

\definecolor{bgcolor}{HTML}{E0E0E0}
\let\oldtexttt\texttt

\renewcommand{\texttt}[1]{
  \colorbox{bgcolor}{\oldtexttt{#1}}
  }
```
Now inline code appears gray when you use ` `` `

**Comment by Wandmalfarbe** [comment]
> Another solution from: https://jdhao.github.io/2019/05/30/markdown2pdf_pandoc/

This only works with the default inline code not when using `listings`.

**Comment by cagix** [comment]
@Stefan-Ilic you could also wrap your lstlistings in a tcolorbox, like proposed in  https://github.com/Wandmalfarbe/pandoc-latex-template/issues/183#issuecomment-682390772
