### ISSUE TITLE
File eisvogel.latex not found in resource path

### ISSUE THREAD

**Issue by mrichman** [Wandmalfarbe/pandoc-latex-template#49]
I have `eisvogel.latex` (renamed from eisvogel.tex) in `$HOME/.pandoc/templates`.

When I run `pandoc my.md -o my.pdf --from markdown --template eisvogel --listings` I get the error:

`File eisvogel.latex not found in resource path`

Please advise.

**Comment by Wandmalfarbe** [comment]
There seems to be an issue with the user data directory and the lookup of latex files in version `2.1.2`:

> Fix regression finding templates in user data directory ([#4777](https://github.com/jgm/pandoc/issues/4777)). Under version 2.2.1 and prior pandoc found latex templates in the templates directory under the data directory, but this broke in 2.2.2.

The new pandoc version `2.2.2` should fix this issue. You can download it from the [release page](https://github.com/jgm/pandoc/releases).

**Comment by mrichman** [comment]
I'm on 2.2.2:

```
pandoc --version
pandoc 2.2.2
Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2
Default user data directory: /User/Mark/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by mrichman** [comment]
I was able to work around this by using `--template ~/.pandoc/templates/eisvogel.latex`

**Comment by Wandmalfarbe** [comment]
Hm, this is definitley strange. It seems to be an upstream issue with pandoc. You can open an issue there or use the workaround with the full path.

**Comment by hidde-jan** [comment]
Bug seems present in Pandoc 2.3.1. Pandoc doesn't even look in the data-dir it seems.

**Comment by kopax** [comment]
I have the same issue with pandoc 2.7.3, should `--data-dir`  be fixed?

**Comment by cagix** [comment]
according to the [pandoc manual](https://pandoc.org/MANUAL.html) in section "General writer options" pandoc would search for template files in `$DATADIR/templates/`, where `$DATADIR` can be specified using the `--data-dir` option

**Comment by cagix** [comment]
just tried this (pandoc 2.7.3): created a subfolder `templates/` in my working copy, copied `eisvogel.tex` to this subfolder, opened a terminal at `examples/book/` and issued `pandoc book.md -o book.pdf --template eisvogel.tex --data-dir ../../` ... worked pretty well :)

ok,  `pandoc book.md -o book.pdf --template  ../../eisvogel.tex` works, too ...
