### ISSUE TITLE
Support multiple authors?

### ISSUE THREAD

**Issue by iandol** [Wandmalfarbe/pandoc-latex-template#5]
Hi, in the basic Pandoc template you can use multiple authors in the YAML metadata:

```yaml
author:
  - Joe Bloggs
  - Joanne Bloggs
```

However, if I use multiple authors with your template then compiling the TeX file breaks:

```
! Misplaced \crcr.
\endarray ->\crcr
                  \egroup \egroup \gdef \@preamble {}\CT@end
l.289 ...\textsf{\uppercase{Joe Bloggs \and Joanne Bloggs}}
```

**Comment by Wandmalfarbe** [comment]
Does this commit fix your problem?

**Comment by iandol** [comment]
Yes, it does, thanks!
