### ISSUE TITLE
How to change default template settings?

### ISSUE THREAD

**Issue by skymal4ik** [Wandmalfarbe/pandoc-latex-template#52]
Hello!

How can I change default template settings, like titlepage-color. titlepage-rule-color, listings-disable-line-number, etc?

Now I save those values in my .md files like that:

```
titlepage-color: ff0000
titlepage-rule-color: 00ff00
listings-disable-line-numbers: true
...
```

But as all my documents should look same, I need to add those lines in every source document.

This would ease document management. 

Checked document management and wiki, but wasn't able to find how to change them. 

Thank you a lot!

**Comment by Wandmalfarbe** [comment]
You need to add these lines to every markdown document exactly like so:

```markdown
---
title: "The Document Title"
author: [Example Author, Another Author]
date: 2017-02-20
keywords: [Markdown, Example]
titlepage-color: "FF0000"
titlepage-rule-color: "00FF00"
listings-disable-line-numbers: true
...

Some text here. Here is some text.
```

**Comment by skymal4ik** [comment]
That's exactly what I'm doing currently.  But I was thinking of changing default values in eisvogel.tex file, so no need to add those values to every md file.

Sorry, I'm not much into TeX, wasn't able to find those values in eisvogel.tex,

**Comment by Wandmalfarbe** [comment]
You can search the variables like `titlepage-color` in the template file and replace the occuring `$titlepage-color$` with something you like. 

Moreover, pandoc allows to set metadata via a file so you could make a YAML file with your custom settings like so:

```yaml
titlepage-color: "FF0000"
titlepage-rule-color: "00FF00"
listings-disable-line-numbers: true
```

and specify this file every time you compile your markdown like so:

```bash
pandoc document.md metadata.yaml -o document.pdf
```

Please have a look in the [pandoc manual under YAML metadata block](http://pandoc.org/MANUAL.html#extension-yaml_metadata_block).
