### ISSUE TITLE
Error producing PDF with **`#;`**

### ISSUE THREAD

**Issue by pseigo** [Wandmalfarbe/pandoc-latex-template#60]
I am trying to convert a markdown file to a PDF using the Eisvogel template. My input file has lots of bold, italics, lists, backtick code sections and triple backtick code sections. Pandoc crashes when producing a PDF only containing \*\*\`#;\`\*\*.

## Steps to Reproduce
1. Create a `.md` file with contents:
```
**`#;`**
```
2. Run `pandoc example.md -o example.pdf --from markdown --template eisvogel --listings`, where `example.md` is the name of the file

## The error

When producing a markdown file named `example.md` with the contents

```md
**`#;`**
```

and running `pandoc example.md -o example.pdf --from markdown --template eisvogel --listings`, I get the output

```
Error producing PDF.
! Illegal parameter number in definition of \reserved@a.
<to be read again>
                   ;
l.327 \textbf{\passthrough{\lstinline!#;!}}
```

## Environment

Windows 10.

```
pandoc.exe 2.3
Compiled with pandoc-types 1.17.5.1, texmath 0.11.1, skylighting 0.7.2
```

**Comment by Wandmalfarbe** [comment]
Thank you for reporting that issue. It seems that this is an upstream problem that exists in the default LaTeX template as well. I suggest you open an issue at the [pandoc issue tracker](https://github.com/jgm/pandoc/issues) and I will merge any resulting template changes to this repository.

**Comment by Wandmalfarbe** [comment]
This bug is fixed in the latest pandoc.
