### ISSUE TITLE
titlegraphic usage ?

### ISSUE THREAD

**Issue by dgoosens** [Wandmalfarbe/pandoc-latex-template#61]
Hi,

I'm no expert at all at latex, but it appears to be possible to insert a `titlegraphic` somehow...  
Could anybody show me how that works cuz I fail miserably.

Tried:

- full path
- relative path
- markdown format
- html format

Thanks in advance

**Comment by Wandmalfarbe** [comment]
I just added the variable `logo` in commit https://github.com/Wandmalfarbe/pandoc-latex-template/commit/7f36404e0bd194142853752d20eb65844217f602 to display an image/logo on the titlepage. The path you specify there has to be relative to where you execute pandoc.

**Comment by dgoosens** [comment]
hi @Wandmalfarbe  
geez... that was fast... did not expect that...  
Thanks !

LOL...  
The thing is, I spend an hour or so to try to deal with it myself (not a latex expert at all) and was pretty proud of the result and was going to submit a PR.

I compared your (left) and my (right) solution: 

![selection_002](https://user-images.githubusercontent.com/1250047/46041922-58e96e80-c114-11e8-9088-a5a8bd8ca1e9.png)

Clearly both don't do the same...  
I was looking for a real visual on the titlepage...

So I created two new variables:

```yaml
titlepage-image: "%%IMAGE IN THE SAME DIRECTORY AS THE MD%" 
titlepage-image-height: %%HEIGHT IN CM%%
```

This fits **my** needs, and it probably hasn't been implemented as it should have been...  
But if it is of your interest to include this, let me know and I'll submit a PR

[eisvogel_dgoosens.zip](https://github.com/Wandmalfarbe/pandoc-latex-template/files/2417009/eisvogel_dgoosens.zip)

@dgoosens
