### ISSUE TITLE
Multiple source files

### ISSUE THREAD

**Issue by kapilsharma** [Wandmalfarbe/pandoc-latex-template#63]
Hi, Thanks for the awesome project.

Is it possible to have multiple source files? For a book, I prefer to have separate markdown files for each chapter. I tried following command

```Bash
pandoc --template eisvogel --listings -o TestBook.pdf 01-About.md 02-install.md
```

However, only contents of first markdown file `01-about.md` appears in pdf while second file `02-install.md` is ignored.

Again, Is it possible to add some option to not number few sections like about, perfect etc. (All books have few such sections before first chapter)

**Comment by daamien** [comment]
Hi !

If multiple input files are given, pandoc will concatenate them all (with blank lines between them) before parsing. You can check this
You can easily check this with this test:
```
echo a > a.md
echo b > b.md
pandoc -o c.txt a.md b.md
cat c.txt
```
see https://github.com/jgm/pandoc/blob/master/MANUAL.txt#L61

Headers with the class `unnumbered` will not be numbered, even if --number-sections is specified. A single hyphen (-) in an attribute context is equivalent to .unnumbered, and preferable in non-English documents. So,

```
# My header {-}
```

is just the same as
```
# My header {.unnumbered}
```

see https://github.com/jgm/pandoc/blob/master/MANUAL.txt#L2194

**Comment by Wandmalfarbe** [comment]
Thank you @daamien for the excellent answer.

**Comment by daamien** [comment]
@Wandmalfarbe: Thanks for your work on this template, it is a truely wonderful project :)
