### ISSUE TITLE
footnote's link jumps to the beginning of the PDF file

### ISSUE THREAD

**Issue by apraile** [Wandmalfarbe/pandoc-latex-template#64]
Hi,
The problem is that in the produced PDF file clicking footnote reference link doesn't jump to footnote definition in bottom of the page, instead, it jumps to the beginning of the PDF file.
I think the problem may be in the order in which the packages `setspace` and `hyperref` are loaded (see: https://tex.stackexchange.com/q/188273).

Test environment:
- Pandoc v.2.3.1
- [Markdown example](https://gist.githubusercontent.com/apraile/5cf07bfcc6454e8ad65a266e175b3b11/raw/14734aa4bf78519c7be4e305ec3243c474431989/example-footnote.md)
- Command: `pandoc example-footnote.md -o example-footnote.pdf --from markdown --template eisvogel`

Thanks.

**Comment by Wandmalfarbe** [comment]
Thanks for the bug report and the hint how to solve it! The broken footnote links should work now.
