### ISSUE TITLE
Error producing PDF, Missing \begin{document}

### ISSUE THREAD

**Issue by steven-jeanneret** [Wandmalfarbe/pandoc-latex-template#65]
I'm trying to convert md file to pdf file and I got this error.
I used your template 4 month ago and it worked great but now I can't make it work again.

I tried with an old report and with simple text like "hi" in the file and I won't work.
If I don't use your template it work and I tried with backup of your template who worked 4 month ago and the new one and I can't make it work.
I'm on arch so I got the last version of texlive, I hav the same issue on a server with Ubuntu 17.04.

The exact error I get with verbose :
```
[makePDF] Run #1
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018/Arch Linux) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./tex2pdf.-5c627415efb288e2/input.tex
LaTeX2e <2018-04-01> patch level 5

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.7 <
     !DOCTYPE html>
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on ./tex2pdf.-5c627415efb288e2/input.log.

[makePDF] Run #2
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018/Arch Linux) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./tex2pdf.-5c627415efb288e2/input.tex
LaTeX2e <2018-04-01> patch level 5

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.7 <
     !DOCTYPE html>
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on ./tex2pdf.-5c627415efb288e2/input.log.

Error producing PDF.
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.7 <
```

I don't really know what to try, if you someone has an idea it would be nice?

**Comment by steven-jeanneret** [comment]
If I open the eisvogel.tex file in PyCharm, it highlight somethings :
```
\renewenvironment{quote}{\begin{customblockquote}\list{}{\rightmargin=0em\leftmargin=0em}%
\item\relax\color{blockquote-text}\ignorespaces}{\unskip\unskip\endlist\end{customblockquote}}
```
after `\ignorespaces}` it says : `<no math content>, <parameter>, LatexTokenType.* or LatexTokenType.\end expected, got '}`

But I don't know latex and I don't know how pandoc template work so I'm not sure that's the problem.

**Comment by Wandmalfarbe** [comment]
It looks like you downloaded an html page instead of the file `eisvogel.tex`. I can see this from your error description here:

```
l.7 <
     !DOCTYPE html>
!  ==> Fatal error occurred, no output PDF file produced!
```

Of course LaTeX doesn't understand html and chokes on it. Please make sure you [download the correct file](https://github.com/Wandmalfarbe/pandoc-latex-template/archive/master.zip).
