### ISSUE TITLE
Add support for NO page break in code block

### ISSUE THREAD

**Issue by wollanup** [Wandmalfarbe/pandoc-latex-template#66]
I use your template to generate code documentation from markdown, with lot of code blocks.
I have issues with page breaks inside a code block which I would like to avoid.

**Output PDF :**

![capture d ecran de 2018-11-02 11-16-04](https://user-images.githubusercontent.com/4822805/47909626-c5345c00-de90-11e8-8d6f-52ffce8765fe.png)

I've edited your template and added following code after `$if(listings)$` block :

```tex
$if(listings-no-page-break)$
\usepackage{etoolbox}
\BeforeBeginEnvironment{lstlisting}{\par\noindent\begin{minipage}{\linewidth}}
\AfterEndEnvironment{lstlisting}{\end{minipage}\par\addvspace{\topskip}}
$endif$
```
And i use this option in my YAML header : 
```yml
listings-no-page-break: true
```

**Output PDF :**

![capture d ecran de 2018-11-02 11-17-46](https://user-images.githubusercontent.com/4822805/47909724-03ca1680-de91-11e8-821d-f4166fe8cc22.png)

This is not a perfect solution because if code block is longer than 1 page, there is no page break at all, the code block overflows on footer and content goes below the page.

I'm really not an expert in pandoc/latex but it's the best solution I found so far. Maybe you coud tweak this and add it in your template ?

Thank you for your work.

[EDIT] : [Added PR](https://github.com/Wandmalfarbe/pandoc-latex-template/pull/67/files).

**Comment by Wandmalfarbe** [comment]
Thank you for this contribution. I agree that this is not a perfect solution, but seems useful with many small listings inside a document.
