### ISSUE TITLE
XeLaTeX and Custom Title page

### ISSUE THREAD

**Issue by iandol** [Wandmalfarbe/pandoc-latex-template#7]
If I use XeLaTeX and your custom page, the blue background leaks into the next page. Compiling with LuaLaTeX of PDFTeX and it works fine.

![screen shot 2017-05-26 at 20 56 56_small](https://cloud.githubusercontent.com/assets/153905/26495474/4fccb642-4256-11e7-8856-c5ae494cacf0.png)

**Comment by Wandmalfarbe** [comment]
That's really strange behavior. Now I use a package for changing the color and everything seems to work. Let me know if you still have problems.

**Comment by iandol** [comment]
This is now fixed, thank you!
