### ISSUE TITLE
Pictures in header

### ISSUE THREAD

**Issue by MisterFossey** [Wandmalfarbe/pandoc-latex-template#71]
Hi,

is it possible to add an image (logo in what ever format) to the header/footer?

**Comment by Wandmalfarbe** [comment]
Currently the template doesn’t provide a way to do this. However you can always tweak the code yourself and send a pull request.

**Comment by domiSchenk** [comment]
just want to let you know, you can use markdown for this:
`header-right: "![](logo.png)"`
unfortunately width does not work

**Comment by johannesmols** [comment]
This can also be achieved like this in the metadata block: `header-right: \includegraphics[width=3cm]{logo.pdf}`
