### ISSUE TITLE
top margin before H1 headings

### ISSUE THREAD

**Issue by SirMossi** [Wandmalfarbe/pandoc-latex-template#72]
first of all thank you for this excellent template.

I have no experience with latex and therefore I am a bit awkward when I want to customize the template for my needs.
I have a page break in front of the H1 headers. However, the H1 headings have a top margin. Is there any way to remove this margin?

**Comment by Wandmalfarbe** [comment]
Would you mind sharing a screenshot of your PDF, so I can better understand what you're trying to achive?

**Comment by SirMossi** [comment]
First of all, I wish you a Merry Christmas.
I have attached a screenshot of a book where I can show the "problem". The book is about Alice in Wonderland, which I prepared as Markdown as an example.
In the attached zip I have inserted some source files with which I want to create the PDF.
My goal is that the headings (chapter...) also start as high up as possible.

![sample](https://user-images.githubusercontent.com/14142661/50426672-5d98fc80-0894-11e9-8368-6a6add0e5523.png)
[sample.zip](https://github.com/Wandmalfarbe/pandoc-latex-template/files/2709048/sample.zip)

Thank you and best regards

**Comment by Wandmalfarbe** [comment]
Thats the default chapter style of the [KOMA-script](https://ctan.org/pkg/koma-script) package. When you use the book option there should be no headers on chapter pages per default. I don't know why your example has headers on chapter pages but you can look in the examples folder (in the `book` folder and `build.sh` script) to see how a book is rendered.

I didn't test this but you should be able to [remove the top margin like shown in these stackoverflow answers](https://tex.stackexchange.com/questions/43087/remove-space-before-chapter-title-with-koma-script-scrbook).

**Comment by SirMossi** [comment]
Thank you so much for pointing that out. I added the following line and now it looks like I expected it to.

    \renewcommand{\chapterheadstartvskip}{}
