### ISSUE TITLE
verbatim in lists

### ISSUE THREAD

**Issue by craigpla** [Wandmalfarbe/pandoc-latex-template#73]
Someone showed me your template last month. While I didn't end up using it, it gave me hope. I've since concocted my own, and wondered about something in yours. I'm having a problem where verbatim text has space above it that inline code doesn't, when it's nested in a list. You too have some space, but it's not as pronounced. I haven't figured out yet how you did it. I see you're using the fancyvrb package, but is that how you've got less space? I can't seem to find a list anywhere of all its options, so I don't know what to look for in your template.

**Comment by Wandmalfarbe** [comment]
The default environment for code and code blocks is verbatim. I have not styled this environment (directly) so everything should look more or less like in the [standard pandoc template](https://github.com/jgm/pandoc/blob/master/data/templates/default.latex). 

I mostly [use listings](https://github.com/Wandmalfarbe/pandoc-latex-template/blob/master/examples/listings/listings.pdf) as the environment for rendering code [which I modified heavily](https://github.com/Wandmalfarbe/pandoc-latex-template/blob/master/eisvogel.tex#L593). The top and bottom margins are controlled with `aboveskip` and `belowcaptionskip`. I hope you can figure how to modify your template. It might help to exclude all the if statements and see what LaTeX is actually used to create the PDF document. You can simply render your markdown to LaTeX:

```
pandoc example.md -o example.latex --template eisvogel --listings
```
