### ISSUE TITLE
Default footer text can't be overwritten.

### ISSUE THREAD

**Issue by MeTavi** [Wandmalfarbe/pandoc-latex-template#75]
It seems to be a bug...  I've updated the metadata section, at the top of the markdown file with no luck in updating the produced pdf to show a different 'footer-left' and have a separate page for 'toc'.

```
--
title: "My   ##Title"
author: "My Name"
titlepage: True
footer-left: "xyz"
toc-own-page: True
...
```

**Comment by Wandmalfarbe** [comment]
This works perfectly fine for me with the following markdown:

```
---
title: "My Title"
author: "My Name"
titlepage: true
footer-left: "text footer left"
toc-own-page: true
toc: true
...

# Hello

## World
```

It looks like you forgot the last hypen (`-`) of your YAML frontmatter in the first line.
