### ISSUE TITLE
How to indent toc

### ISSUE THREAD

**Issue by vncoelho** [Wandmalfarbe/pandoc-latex-template#80]
We are trying to indent toc chapter, section and subsection.
![image](https://user-images.githubusercontent.com/17395762/54232255-ff6dd400-44e8-11e9-9adf-95353d1b5207.png)

For example, 4.1 to be a little bit more in the right.

**Comment by Wandmalfarbe** [comment]
I don't understand what you are trying to archive. The default table of contents looks like this:

<img width="717" alt="Screenshot 2019-03-13 12 20 03" src="https://user-images.githubusercontent.com/17237627/54275299-93dc4300-458a-11e9-8fc3-821f00583daf.png">

**Comment by vncoelho** [comment]
Hi @Wandmalfarbe, sorry for the confusion, we were using another template. AHueahueaea
We switched to yours. Thanks,
