### ISSUE TITLE
[QUESTION] Reference section with title

### ISSUE THREAD

**Issue by vncoelho** [Wandmalfarbe/pandoc-latex-template#82]
We would like to include the Reference section in the contents without numbering, is there an easy way to achieve that?

Currently, references are being include at the end without title.

Another possibility that may be useful to us would be to create specific references for each chapter, could you recommend any path to do that?

Thanks,

**Comment by Wandmalfarbe** [comment]
> We would like to include the Reference section in the contents without numbering, is there an easy way to achieve that?
> Currently, references are being include at the end without title.


Please take a look in the manual under [Citations](https://pandoc.org/MANUAL.html#citations) and [Citation Rendering](https://pandoc.org/MANUAL.html#citation-rendering). You can insert a non numbered heading for the references when using the filter `--filter pandoc-citeproc` and the metadata field `reference-section-title: "References"`.

```markdown
---
bibliography: Masterarbeit.bib
reference-section-title: "References"
...

# My Document
```

>Another possibility that may be useful to us would be to create specific references for each chapter, could you recommend any path to do that?


Pandoc automatically creates labels for each heading (chapters and sections) but you can override them with your own label. Take a look at the following markdown and the [correspoding LaTeX-Output](https://pandoc.org/try/?text=%23+The+First+Chapter%0A%0ASome+Text+here.%0A%0A%23%23+The+First+Section+%7B%23my-custom-label%7D%0A%0ASome+Text+here.+This+is+a+link+to+%5Bthe+first+chapter%5D(%23the-first-chapter).+This+is+a+link+to+the+%5Bfirst+section%5D(%23my-custom-label).&from=markdown&to=latex).

```markdown
# The First Chapter

Some Text here.

## The First Section {#my-custom-label}

Some Text here. This is a link to [the first chapter](#the-first-chapter). This is a link to the [first section](#my-custom-label).
```

**Comment by vncoelho** [comment]
Eahueahuea, @Wandmalfarbe, the last question was related to include "Bibliography References" at the end of each chapter instead of just at the end of the "book".

**Comment by Wandmalfarbe** [comment]
Hm, I dont think that is a common use case even in the LaTeX world. You can try googling around a bit how to make it work in LaTeX and include any custom commands and such via *header-includes*.

**Comment by vncoelho** [comment]
Roger that, thanks for your attention and help.
