### ISSUE TITLE
Missing Figure titile 

### ISSUE THREAD

**Issue by huyhoang8398** [Wandmalfarbe/pandoc-latex-template#83]
My figure title unfortunately disappear when i convert a markdown file to pdf using this template

**Comment by huyhoang8398** [comment]
closed, i fixed with 
  \begin{figure}
  \centering
  {\includegraphics[width=2.5in]{TsTJy7N.png}}
  \caption{Grid of reference points on USTH building's 5th floor}
  \end{figure}
instead of 
![title]{.img}

**Comment by Wandmalfarbe** [comment]
I think you are using an old pandoc version. Images with a description should have captions in LaTeX and PDF output. Please take a look at the [images and tables example](https://github.com/Wandmalfarbe/pandoc-latex-template/tree/master/examples/images-and-tables). You don't need to use raw latex to include an image with caption.

**markdown input**

```markdown
## Image with Caption

![Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id.](image.png)
```

**PDF output**

<img width="779" alt="Screenshot 2019-03-17 12 54 10" src="https://user-images.githubusercontent.com/17237627/54490178-e16eed80-48b3-11e9-912b-7958cacbf331.png">

**Comment by huyhoang8398** [comment]
Thank you, i just noticed that im currently using pandoc v1.17 :( the newest version is 2.17. time to switch to the newer version, thank you so much
