### ISSUE TITLE
"Environment abstract undefined" when using -V book:true

### ISSUE THREAD

**Issue by jdittrich** [Wandmalfarbe/pandoc-latex-template#88]
**Actions:** Trying to generate a pdf using … `--from markdown --template eisvogel -V titlepage:true -V book:true`…

**Expected Outcome:** A PDF with book-typesetting

**Actual Outcome:**
Error on command line: 

`Error producing PDF.` 

`! LaTeX Error: Environment abstract undefined.`
…
`l.317 \begin{abstract}`

The error did not occur, when book:true was not set. 

I assume that it tries to give an abstract section, but the book class has no "abstract" defined

**Comment by jdittrich** [comment]
A quick fix is to set `--metadata=abstract:" "`
since an empty string will evaluate to false: 

> Here a truthy value is any of the following:
> * a string that is not entirely white space,

([Pandoc Manual](http://pandoc.org/MANUAL.html#using-variables-in-templates))

**Comment by jdittrich** [comment]
A quick fix is to set `--metadata=abstract:" "`
since an empty string will evaluate to false: 

> Here a truthy value is any of the following:
> * a string that is not entirely white space,

([Pandoc Manual](http://pandoc.org/MANUAL.html#using-variables-in-templates))

**Comment by Wandmalfarbe** [comment]
I can't reproduce this bug. I tried it with these commands and everything compiles fine:

```
pandoc file.md -o file-pdflatex.pdf --from markdown --template eisvogel -V titlepage:true -V book:true --pdf-engine pdflatex
pandoc file.md -o file-xelatex.pdf  --from markdown --template eisvogel -V titlepage:true -V book:true --pdf-engine xelatex
```

What version of pandoc are you using? Can you show me your source markdown document?

**Comment by jdittrich** [comment]
I checked again. The error still occurs with the most recent pandoc.  

It does only occur when there is an abstract set, in my case in [the YAML file I include](https://github.com/jdittrich/userNeedResearchBook/blob/master/text/URBookMetadata.yaml).

It also happens if the source *.md* file has a YAML section which sets an abstract.

**Comment by Wandmalfarbe** [comment]
Yes, I can confirm this. The LaTeX class `book` and the KOMA script class `scrbook` don't support an abstract environment.

> Books typically use a different kind of summary. There, you usually place an appropriate chapter at the beginning or the end of the work. This chapter is often combined with either the introduction or a description of a larger prospectus. Therefore, the scrbook class has no `abstract` environment.

You could define your own `abstract` environment in the LaTeX preamble via `header-includes`. I'll have to research a bit on how to do that.

**Comment by Wandmalfarbe** [comment]
Of course you can also sprinkle a bit of LaTeX code inside your markdown document:

```markdown
\begin{addmargin}[3em]{3em}
\begin{singlespacing}
\section*{Abstract}

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.

\end{singlespacing}
\end{addmargin}

## My Heading

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
```
