### ISSUE TITLE
Subtitle not working

### ISSUE THREAD

**Issue by alainmuls** [Wandmalfarbe/pandoc-latex-template#90]
Dear Pascal,

A very lovely package which I am trying out now. I wanted to get a subtitle on my title page and added to the YAML section under "title" the following:

subtitle: "My sub title that I want"

In your template file, the $iif(subtitle)$ section is present, but the subtitle is not displayed.

Maybe you can point me in the right direction?

Kind regards
Alain

**Comment by Wandmalfarbe** [comment]
Please take a look at the [green titlepage example](https://github.com/Wandmalfarbe/pandoc-latex-template/tree/master/examples/green-titlepage). You need to have a titlepage in order for the subtitle to appear in the PDF. The following YAML block in your markdown generates a green titlepage with a subtitle:

```markdown
---
title: "Vinaque sanguine metuenti cuiquam Alcyone fixus"
author: [Author Name]
date: "2017-02-20"
subject: "Markdown"
keywords: [Markdown, Example]
subtitle: "Aesculeae domus vincemur et Veneris adsuetus lapsum"
lang: "en"
titlepage: true
titlepage-color: "3C9F53"
titlepage-text-color: "FFFFFF"
titlepage-rule-color: "FFFFFF"
titlepage-rule-height: 2
...

Here is the document text.
```
