### ISSUE TITLE
Code blocks too close to text

### ISSUE THREAD

**Issue by tschinz** [Wandmalfarbe/pandoc-latex-template#91]
Hello, my code blocks are too close to the text. Sometimes even cuts off a complete line
![image](https://user-images.githubusercontent.com/1192968/56130575-98c75480-5f85-11e9-8fef-54f972c504ba.png)
![image](https://user-images.githubusercontent.com/1192968/56130584-9d8c0880-5f85-11e9-8434-27cc313a5d6e.png)

**Comment by Wandmalfarbe** [comment]
I can't reproduce this issue. Could you send me your document with the command you are using to render The PDF? What version of pandoc are you using?

**Comment by tonghuix** [comment]
I use identical repo but using xelatex, can reproduce this issue.

**Comment by oripka** [comment]
This markdown reproduces the issue
```
XXXXX YYYYYYYYYY  `OOOOOO` OVERFLOWOVERFLOWOVERFLOWOVERFLOWOVERFLOWOVERFLOWOVERFLOWOVERFLOWOVERFLOWOVERFLOW.

    LISTING BLOCK 
    ----------------
    LISTING BLOCK 
```

Compiling with

`pandoc bug.md -o bug.pdf --template eisvogel.tex  --listing`

**Comment by oripka** [comment]
This commit introduced the issue: https://github.com/Wandmalfarbe/pandoc-latex-template/commit/5046ee08cdfd7b037b4f4281ffe77f0ad266ced1.

The problem is the negative `aboveskip`:

```aboveskip        = -0.7em,```

Changing it back to 

```aboveskip        = 1.0em,```

solves the issue.

**Comment by tschinz** [comment]
I can confirm that this solves the issue. Thanks @oripka

**Comment by Wandmalfarbe** [comment]
That is strange because I still can't reproduce the issue.

<img width="752" alt="Screenshot 2019-04-21 12 35 57" src="https://user-images.githubusercontent.com/17237627/56468861-51800e80-6432-11e9-8ff0-53900af78792.png">

@oripka, @tschinz can you please post the output of `latex --version`. Maybe you have an old version installed. Are you using MiKTeX or TeX Life? On Windows, macOS or Linux?

**Comment by oripka** [comment]
This is on macOs:

```
latex --version
pdfTeX 3.14159265-2.6-1.40.19 (TeX Live 2018)
kpathsea version 6.3.0
Copyright 2018 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.34; using libpng 1.6.34
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.00
````

![issue](https://user-images.githubusercontent.com/227032/56468979-e7686900-6433-11e9-8d0a-2ff5a06dbd9e.png)

**Comment by Wandmalfarbe** [comment]
@oripka Thank you for your help! Could you please update all your installed packages? Open *TeX Live Utility*, click on the tab *Updates*, Select all the packages, right-click them and click update.

**Comment by oripka** [comment]
@Wandmalfarbe Yes that fixes it as well.

**Comment by Wandmalfarbe** [comment]
Phew, and I thought I was going crazy :) Thank you very much for your help!

**Comment by oripka** [comment]
By the way: I recently installed via `brew cask install basictex` and and the other dependencies via `tlmgr`. Which seemed to me like the common way to get Latex running on macOs.

**Comment by davidsan** [comment]
Hi, 

I face the same issue on Windows using MiKTeX with all packages updated (via MiKTeX Console). 

```
λ latex --version
MiKTeX-pdfTeX 2.9.7029 (1.40.20) (MiKTeX 2.9.7050 64-bit)
Copyright (C) 1982 D. E. Knuth, (C) 1996-2018 Han The Thanh
TeX is a trademark of the American Mathematical Society.
using bzip2 version 1.0.6, 6-Sept-2010
compiled with curl version 7.61.1; using libcurl/7.61.1 WinSSL
compiled with expat version 2.2.6; using expat_2.2.6
compiled with jpeg version 9.3
compiled with liblzma version 50020042; using 50020042
compiled with libpng version 1.6.35; using 1.6.35
compiled with libressl version LibreSSL 2.8.2; using LibreSSL 2.8.2
compiled with MiKTeX Application Framework version 4.6961; using 4.6961
compiled with MiKTeX Core version 14.7079; using 14.7079
compiled with MiKTeX Archive Extractor version 1.6882; using 1.6882
compiled with MiKTeX Package Manager version 6.7072; using 6.7072
compiled with poppler version 0.60.1
compiled with uriparser version 0.9.2
compiled with zlib version 1.2.11; using 1.2.11
```

![AcroRd32_2019-05-22_11-01-22](https://user-images.githubusercontent.com/1223876/58161685-00f21000-7c81-11e9-8942-043485569c34.png)

**Comment by Wandmalfarbe** [comment]
To resolve this issue, please follow these steps:

1. Update all your LaTeX packages to the latest version. 
2. If the problem still persists, you may want to uninstall your LaTeX distribution and install the latest one.
3. If the problem still persists you can copy the following code and replace [the four lines here](https://github.com/Wandmalfarbe/pandoc-latex-template/blob/50a425addb39bda7d2b2b7508e9a8a8e2a6dd02b/eisvogel.tex#L661-L664).

    ```
    aboveskip        = 1.0em,
    belowskip        = 0.1em,
    abovecaptionskip = 0em,
    belowcaptionskip = 1.0em,
    ```
