### ISSUE TITLE
Error when document contains Chinese characters.

### ISSUE THREAD

**Issue by cmmei** [Wandmalfarbe/pandoc-latex-template#92]
Ubuntu install Tex Live
```
Error producing PDF.
! Package inputenc Error: Unicode char 文 (U+6587)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.348 \end{document}

Try running pandoc with --pdf-engine=xelatex.
```
But, when running `pandoc example1.md -o example1.pdf --from markdown --template eisvogel --listings --pdf-engine=xelatex` , Warning:
```
[WARNING] Missing character: There is no 文 in font [SourceSansPro-Regular.otf]/OT:script=
[WARNING] Missing character: There is no 档 in font [SourceSansPro-Regular.otf]/OT:script=
[WARNING] Missing character: There is no 标 in font [SourceSansPro-Regular.otf]/OT:script=
[WARNING] Missing character: There is no 题 in font [SourceSansPro-Regular.otf]/OT:script=
```

how to install Chinese font for tex.

**Comment by Wandmalfarbe** [comment]
Text with chinese and japanese characters needs to be rendered with XeLaTeX. Unfortunately Source Sans Pro does not include such characters so you have to use your own font with the option `CJKmainfont`. You can pass it as a command line parameter like so:

```
pandoc example1.md -o example1.pdf --from markdown --template eisvogel --listings --pdf-engine=xelatex -V CJKmainfont=IPAexGothic
```

The font `IPAexGothic` has to be installed on your computer.

**Comment by tonghuix** [comment]
You can also assign a font at the beginning of you markdown file, secton between `---` and `...`, here is what I succsed right now: 

```
CJKmainfont: Noto Serif CJK SC
```

And yes, you have to install Noto Sans Serif CJK font first.

**Comment by cmmei** [comment]
It's OK. Thank you all. 
I install CJK-all by by `apt install latex-cjk-all`, then assign a font at the beginning of markdown file.
