### ISSUE TITLE
LaTeX Error: This NFSS system isn't set up properly

### ISSUE THREAD

**Issue by praton1729** [Wandmalfarbe/pandoc-latex-template#93]
After providing the required  `.sty` files. I tried to produce a pdf file from an md file with the command 
`pandoc README.md -o README.pdf --template eisvogel` but I  get this error:-

```
! LaTeX Error: This NFSS system isn't set up properly.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.253 \begin{document}

pandoc: Error producing PDF
Makefile:11: recipe for target 'README.pdf' failed
make: *** [README.pdf] Error 43
```

How can I resolve it?

**Comment by Wandmalfarbe** [comment]
This doesn't seem to be a problem of the template itself. I suggest updating all your LaTeX packages or uninstalling and then reinstalling your whole TeX distribution.

**Comment by praton1729** [comment]
Yes, that was it. I had to upgrade my texlive installation to a full texlive package, it is named as `texlive-full` in Ubuntu repositories.
