### ISSUE TITLE
More flexible image location

### ISSUE THREAD

**Issue by offray** [Wandmalfarbe/pandoc-latex-template#95]
Hi,

Thanks for this template. I have been using it in [software manuals][gf-manual] with pretty good results so far. 

But I have notice that figures are located always where they called in the text (similar to the `!h` LaTeX directive), which some times creates a lot of white space in text near to such figures, instead of a more flexible layout that is usual in default LaTeX templates. ¿Could figures location policy could be setup as a YAML directive?

Cheers,

[gf-manual]: https://mutabit.com/repos.fossil/grafoscopio/uv/Docs/En/Books/Manual/manual.pdf

**Comment by Wandmalfarbe** [comment]
Thank you for this feature request! I introduced a new variable `float-placement-figure` for such a use case. Please see the README for the available values.

**Comment by offray** [comment]
Thank you for such quick answer. I'm already using the new feature in our [latest booklet draft](https://mutabit.com/repos.fossil/documentaton/uv/es/documentaton.pdf).
