### ISSUE TITLE
Beamer output format not supported

### ISSUE THREAD

**Issue by YourPsychiatrist** [Wandmalfarbe/pandoc-latex-template#97]
When compiling my markdown file to pdf via latex, everything seems to be working fine. However, when I specify `beamer` as output format, pandoc complains about missing data files. I hope I am not at fault here; It would be great if you added slides support!

`Could not find data file templates/eisvogel.beamer` is what it says. I mean I obviously just have the eisvogel.latex in the template directory but adding an extra copy with `.beamer` as extension also doesn't work.

**Comment by Wandmalfarbe** [comment]
I think you have an old version of pandoc installed. The Beamer template and the regular LaTeX template were merged with issue https://github.com/jgm/pandoc/issues/3878. Can you show me the output of `pandoc --version`.

**Comment by YourPsychiatrist** [comment]
I built the (at the time) lates release from source so I am running pandoc 2.7.2

```
$ pandoc --version
pandoc 2.7.2
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
```

**Comment by Wandmalfarbe** [comment]
I opened an issue in the pandoc issue tracker: https://github.com/jgm/pandoc/issues/5585. When you specify the template with the extension directly it should use the correct template file:

```
pandoc --from markdown --to beamer document.md --template eisvogel.latex --o document.pdf
```

Unfortunately an arror occurs when generating the beamer PDF. I filed a separate Issue here: #99
