### ISSUE TITLE
Code blocks are overlapping the text at the top margin

### ISSUE THREAD

**Issue by delley** [Wandmalfarbe/pandoc-latex-template#98]
The values in the following settings appear to be causing the code blocks to overlap the text at the top margin.

```
aboveskip        = -0.7em,
belowskip        = 0.1em,
abovecaptionskip = 0em,
belowcaptionskip = 1em,
```

![Screenshot from 2019-06-09 22-40-47](https://user-images.githubusercontent.com/4206531/59167603-6448c280-8b08-11e9-8665-ee8e76a72292.png)

**Comment by klpeders** [comment]
I see the same problem. All the documents in `Eisvogel/examples` will exhibit this issue after running `build-examples.sh`.

I am on Fedora 30, but same problem on Fedora 29.

**Comment by Wandmalfarbe** [comment]
This is a known issue https://github.com/Wandmalfarbe/pandoc-latex-template/issues/91. Please follow these steps:

1. Update all your LaTeX packages to the latest version. 
2. If the problem still persists, you may want to uninstall your LaTeX distribution and install the latest one.
3. If the problem still persists you can copy the following code and replace [the four lines here](https://github.com/Wandmalfarbe/pandoc-latex-template/blob/50a425addb39bda7d2b2b7508e9a8a8e2a6dd02b/eisvogel.tex#L661-L664).

    ```
    aboveskip        = 1.0em,
    belowskip        = 0.1em,
    abovecaptionskip = 0em,
    belowcaptionskip = 1.0em,
    ```
